Repository ChildMindInstitute/mindlogger-admin, pull requests merged in 2023-07, with the labels that each got.

#585 Feature/M2-2444 Performance Tasks - Flanker connect to the changed API
  src/modules/Builder/features/PerformanceTasks/Flanker/Flanker.const.ts
  src/modules/Builder/features/PerformanceTasks/Flanker/GeneralSettings/ButtonsScreen/ButtonsContent/ButtonsContent.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/GeneralSettings/ButtonsScreen/ButtonsScreen.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/GeneralSettings/FixationScreen/FixationContent/FixationContent.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/GeneralSettings/FixationScreen/FixationScreen.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/GeneralSettings/GeneralSettings.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/GeneralSettings/StimulusScreen/StimulusContent/StimulusContent.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/GeneralSettings/StimulusScreen/StimulusScreen.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/BlockSequences/BlockSequences.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/BlockSequences/BlockSequencesContent/BlockSequencesContent.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/BlockSequences/BlockSequencesContent/BlockSequencesContent.types.ts
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/BlockSequences/BlockSequencesContent/BlockSequencesContent.utils.ts
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/BlockSequences/BlockSequencesContent/ImportSequencesPopup/ImportSequencesPopup.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/RoundOptions/RoundOptions.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/RoundOptions/RoundOptions.utils.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/RoundSettings.tsx
  src/modules/Builder/features/PerformanceTasks/Instruction/Instruction.tsx
  src/modules/Builder/features/PerformanceTasks/Instruction/Instruction.types.ts
  src/modules/Builder/features/PerformanceTasks/Instruction/InstructionContent/InstructionContent.tsx
  src/modules/Builder/features/PerformanceTasks/Instruction/InstructionContent/InstructionContent.types.ts
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.hooks.ts
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.types.ts
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.utils.ts
  src/modules/Builder/hooks/useCurrentActivity.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.const.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.schema.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
  src/modules/Builder/types/Builder.types.ts
  src/resources/app-en.json
  src/shared/components/Table/TableHead/TableHead.styles.ts
  src/shared/components/Uploader/Uploader.styles.ts
  src/shared/components/Uploader/Uploader.tsx
  src/shared/components/Uploader/Uploader.types.ts
  src/shared/state/Applet/Applet.schema.ts
Labels: enhancement, Done

#589 Fix/M2-2431 Remove access popup is displaying incorrect information after remove access procedure
  src/modules/Dashboard/features/Managers/Managers.tsx
  src/modules/Dashboard/features/Managers/Popups/ManagersRemoveAccessPopup/ManagersRemoveAccessPopup.tsx
Labels: bug, Done

#595 M2-2472 section condition 422
  src/modules/Builder/features/ActivityItems/ConditionalPanel/ConditionalPanel.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionContent/SectionContent.styles.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionContent/SectionContent.tsx
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.utils.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
  src/shared/state/Applet/Applet.schema.ts
Labels: bug

#591 Fix/M2-2468 Remove respondents data functionality is not working
  src/modules/Dashboard/api/api.ts
  src/modules/Dashboard/features/Respondents/Popups/EditRespondentPopup/EditRespondentPopup.tsx
  src/modules/Dashboard/features/Respondents/Popups/EditRespondentPopup/EditRespondentPopup.types.ts
  src/modules/Dashboard/features/Respondents/Popups/RespondentsRemoveAccessPopup/RespondentAccessPopup.utils.tsx
  src/modules/Dashboard/features/Respondents/Popups/RespondentsRemoveAccessPopup/RespondentsRemoveAccessPopup.tsx
  src/modules/Dashboard/features/Respondents/Popups/RespondentsRemoveAccessPopup/RespondentsRemoveAccessPopup.types.ts
  src/modules/Dashboard/features/Respondents/Respondents.tsx
Labels: bug, Done

#598 fix: M2-634
  src/modules/Builder/features/AboutApplet/AboutApplet.tsx
  src/shared/consts.tsx
Labels: bug, Done

#600 fix: M2-1020 Items: Photo/Video/Audio/Geolocation button should not be displayed according to design, Mobile Only chip was added to the Item select value
  src/modules/Builder/features/ActivityItems/ItemConfiguration/GroupedSelectSearchController/GroupedSelectSearchController.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/GroupedSelectSearchController/GroupedSelectSearchController.utils.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/AudioRecord/AudioRecord.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/Geolocation/Geolocation.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/ItemInfo/ItemInfo.styles.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/ItemInfo/ItemInfo.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/ItemInfo/ItemInfo.types.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/ItemInfo/index.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/PhotoResponse/PhotoResponse.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/VideoResponse/VideoResponse.tsx
  src/modules/Library/features/AppletsCatalog/AppletsCatalog.conts.tsx
  src/shared/consts.tsx
Labels: bug, Done

#602 Fix/M2-2238 Validation message on edit upload image
  src/shared/components/Uploader/Uploader.tsx
Labels: bug, Done

#603 Fix/M2-2496 DataViz: Start/End date combined picker is shown on clicking either Start or End date
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.utils.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ReportFilters/ReportFilters.tsx
  src/modules/Dashboard/hooks/useDatavizFilters.ts
Labels: bug, Done

#608 Feature/m2 2471 add report files for drawing item
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/AudioPlayer/RecordAudio/RecordAudio.hooks.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Feedback/AssessementItems/MultipleSelection/MultipleSelection.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Feedback/AssessementItems/SingleSelection/SingleSelection.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Feedback/FeedbackAssessment/ActivityCardItemList/ActivityCardItem/ActivityCardItem.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Feedback/FeedbackAssessment/ActivityCardItemList/ActivityCardItem/ItemPicker/ItemPicker.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Feedback/FeedbackAssessment/ActivityCardItemList/ActivityCartItemList.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Feedback/FeedbackAssessment/FeedbackAssessment.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Feedback/FeedbackAssessment/FeedbackAssessmentForm/FeedbackAssessmentForm.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Feedback/FeedbackAssessment/FeedbackAssessmentForm/FeedbackAssessmentForm.utils.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Feedback/FeedbackReviewed/FeedbackReviewer/FeedbackReviewer.const.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/RespondentDataReview.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Review/Review.const.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Review/Review.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.utils.ts
  src/modules/Dashboard/features/Respondents/Popups/DataExportPopup/DataExportPopup.tsx
  src/modules/Dashboard/hooks/useDecryptedActivityData.ts
  src/modules/Dashboard/hooks/useEncryptedAnswers.ts
  src/shared/features/AppletSettings/ExportDataSetting/ExportDataSetting.tsx
  src/shared/types/answer.ts
  src/shared/utils/exportData/exportDataSucceed.ts
  src/shared/utils/exportData/exportLinesZip.ts
  src/shared/utils/exportData/getDrawingLines.ts
  src/shared/utils/exportData/getJourneyCSVObject.ts
  src/shared/utils/exportData/getMediaReportName.ts
  src/shared/utils/exportData/getReportCSVObject.ts
  src/shared/utils/exportData/getReportName.ts
  src/shared/utils/exportData/getSubscales.ts
  src/shared/utils/exportData/index.ts
  src/shared/utils/exportData/parseResponseValue.ts
  src/shared/utils/exportData/prepareData.ts
  src/shared/utils/exportData/replaceItemVariableWithName.ts
  src/shared/utils/exportTemplate.ts
  src/shared/utils/getAnswerValue.ts
Labels: enhancement

#609 feat: M2-2531 Flanker - set value property for Stimulus and Buttons, add constant properties
  src/modules/Builder/features/PerformanceTasks/Flanker/GeneralSettings/ButtonsScreen/ButtonsContent/ButtonsContent.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/GeneralSettings/FixationScreen/FixationContent/FixationContent.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/GeneralSettings/StimulusScreen/StimulusContent/StimulusContent.tsx
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.utils.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.const.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
  src/modules/Builder/types/Builder.types.ts
  src/modules/Dashboard/features/Applet/Schedule/Calendar/Toolbar/Toolbar.types.ts
  src/modules/Dashboard/features/Applet/Schedule/EventForm/AvailabilityTab/AvailabilityTab.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/NotificationsTab/Notification/Notification.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/TimersTab/TimersTab.tsx
  src/shared/components/ToggleButtonGroup/ToggleButtonGroup.tsx
  src/shared/components/ToggleButtonGroup/ToggleButtonGroup.types.ts
  src/shared/state/Applet/Applet.schema.ts
Labels: Done

#610 M2-2507 Data retention save changes popup doesn't close
  src/shared/features/AppletSettings/DataRetentionSetting/DataRetention.tsx
Labels: bug

#613 fix: M2-841
  src/modules/Dashboard/features/Applet/Schedule/Calendar/EventWrapper/EventWrapper.tsx
Labels: bug, Done

#611 Fix/M2-2518, M2-1941 Items: Single Selection Per Row: 422 error after an attempt to save option value with 11+ characters
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SelectionRows/Options/Options.tsx
Labels: bug, Done

#614 fix: M2-843
  src/modules/Dashboard/features/Applet/Schedule/Calendar/EventWrapper/EventWrapper.tsx
Labels: bug, Done

#615 M2-2500 Empty score condition itemName
  src/modules/Builder/components/ConditionRow/ConditionRow.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ConditionContent/ConditionContent.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ConditionContent/ConditionContent.utils.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.utils.ts
Labels: bug

#612 M2-2508 Save changes on setting close
  src/shared/features/AppletSettings/AppletSettings.tsx
Labels: bug

#619 fix: Flanker messages text fix
  src/resources/app-en.json
Labels: bug, Done

#625 M2-2547-edit-applet-empty-screen
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
Labels: bug

#626 M2-2549 Item reset payload in condition
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
Labels: bug

#640 M2-2509 Save changes on logout
  src/modules/Auth/state/Auth.reducer.ts
  src/modules/Auth/state/Auth.schema.ts
  src/modules/Auth/state/Auth.state.ts
  src/modules/Auth/state/index.ts
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.hooks.ts
  src/shared/layouts/BaseLayout/components/TopBar/AccountPanel/AccountPanel.tsx
Labels: bug

#644 M2-2537-2208 Missed respondent name
  src/modules/Dashboard/state/Users/index.ts
Labels: bug

#662 M2-2676 Min score range
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.utils.ts
Labels: bug

#664 M2-2537 Missed respondent name
  src/modules/Dashboard/pages/RespondentData/RespondentData.tsx
Labels: bug

#667 M2-2680 Zero score in export
  src/shared/utils/exportData/parseOptions.ts
Labels: bug

#668 M2-2508 Applet settings close
  src/modules/Dashboard/features/Applet/DashboardAppletSettings/DashboardAppletSettings.utils.tsx
  src/shared/features/AppletSettings/AppletSettings.tsx
  src/shared/features/AppletSettings/DataRetentionSetting/DataRetention.tsx
  src/shared/features/AppletSettings/DataRetentionSetting/Popups/SuccessPopup/SuccessPopup.tsx
  src/shared/features/AppletSettings/DataRetentionSetting/Popups/SuccessPopup/SuccessPopup.types.ts
  src/shared/features/AppletSettings/ReportConfigSetting/Popups/SuccessPopup/SuccessPopup.tsx
  src/shared/features/AppletSettings/ReportConfigSetting/Popups/SuccessPopup/SuccessPopup.types.ts
  src/shared/features/AppletSettings/ReportConfigSetting/ReportConfigSetting.tsx
  src/shared/state/Applet/Applet.utils.ts
  src/shared/state/Applet/index.ts
Labels: bug

#672 M2-2678 Untoggled report switches
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
Labels: bug

#678 M2-2718 Zero max score range
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.utils.ts
Labels: bug

#684 M2-2702 Lookup table parsing error
  src/modules/Builder/features/ActivitySettings/SubscalesConfiguration/LookupTable/LookupTable.utils.tsx
  src/shared/components/FileUploader/FileUploader.tsx
  src/shared/components/FileUploader/FileUploader.types.ts
Labels: bug

#689 M2-2491 Hide add applet
  src/modules/Dashboard/features/Applets/Applets.tsx
  src/modules/Dashboard/features/Applets/Applets.utils.ts
  src/shared/layouts/BaseLayout/components/LeftBar/LeftBar.tsx
  src/shared/utils/getIsAddAppletBtnVisible.ts
  src/shared/utils/index.ts
Labels: bug
