Repository ChildMindInstitute/mindlogger-admin, pull requests merged in 2023-10, with the labels that each got.

#1038 fix: M2-3658 If some Setting (Applet Settings, Activity Settings) in Builder has validation error, according Tab and Setting must be highlighted.
  src/modules/Builder/features/ActivitySettings/ActivitySettings.tsx
  src/modules/Builder/features/ActivitySettings/ActivitySettings.types.ts
  src/modules/Builder/features/ActivitySettings/ActivitySettings.utils.tsx
  src/modules/Builder/pages/BuilderActivity/BuilderActivity.tsx
  src/modules/Builder/pages/BuilderActivity/BuilderActivity.utils.tsx
  src/shared/components/NavigationMenu/LeftBar/LeftBar.styles.ts
  src/shared/components/NavigationMenu/LeftBar/LeftBar.tsx
  src/shared/components/NavigationMenu/NavigationMenu.types.ts
Labels: Done

#1035 fix: M2-3649 Update Flanker Block Sequences if some element of the Stimulus Screen was changed.
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/BlockSequences/BlockSequencesContent/BlockSequencesContent.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/BlockSequences/BlockSequencesContent/BlockSequencesContent.types.ts
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/BlockSequences/BlockSequencesContent/BlockSequencesContent.utils.ts
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/BlockSequences/BlockSequencesContent/ImportSequencesPopup/ImportSequencesPopup.hooks.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/BlockSequences/BlockSequencesContent/ImportSequencesPopup/ImportSequencesPopup.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/BlockSequences/BlockSequencesContent/ImportSequencesPopup/ImportSequencesPopup.types.ts
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/BlockSequences/BlockSequencesContent/ImportSequencesPopup/ImportSequencesPopup.utils.tsx
  src/shared/components/Uploader/ActionButtons/ActionButtons.styles.ts
  src/shared/components/Uploader/Uploader.tsx
Labels: Done

#1040 fix: M2-3659 Cannot navigate from Builder -> Applet Settings -> Report Configuration
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.hooks.ts
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.utils.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
  src/shared/features/AppletSettings/ReportConfigSetting/ReportConfigSetting.hooks.ts
Labels: Done

#1044 fix: M2-3677 Builder - make tabs highlighted wit the red dot on Save and Publish button click
  src/modules/Builder/pages/BuilderActivityFlow/BuilderActivityFlow.utils.tsx
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.utils.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Feedback/Feedback.const.tsx
  src/modules/Dashboard/pages/Applet/Applet.hooks.tsx
  src/modules/Dashboard/pages/Main/Main.const.tsx
  src/modules/Dashboard/pages/RespondentData/RespondentData.hooks.tsx
  src/shared/components/Tabs/LinkedTabs/LinkedTabs.tsx
  src/shared/components/Tabs/Tabs.styles.tsx
  src/shared/components/Tabs/Tabs.types.ts
Labels: Done

#1052 fix: M2-3696 Write unit tests for some shared functions (array.ts, getDateTime.ts, getAnswerValue.ts)
  src/shared/utils/array.test.ts
  src/shared/utils/array.ts
  src/shared/utils/getAnswerValue.test.ts
  src/shared/utils/getDateTime.test.ts
  src/shared/utils/getDateTime.ts
Labels: Done

#1056 fix: M2-3724 Cannot save Applet with Activity with Single/Multiple Selection Item, if option(s) text length is more than expected characters
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SelectionOption/SelectionOption.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SelectionRows/CharactersCounter/CharactersCounter.styles.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SelectionRows/CharactersCounter/CharactersCounter.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SelectionRows/CharactersCounter/CharactersCounter.types.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SelectionRows/SelectionRows.styles.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ItemConfiguration.const.tsx
  src/modules/Builder/hooks/index.ts
  src/modules/Builder/hooks/useFieldLengthError.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.schema.ts
  src/modules/Dashboard/features/Respondents/Popups/EditRespondentPopup/EditRespondentPopup.tsx
  src/shared/components/FormComponents/InputController/Input/Input.styles.ts
  src/shared/components/FormComponents/InputController/Input/Input.tsx
  src/shared/components/FormComponents/InputController/InputController.types.ts
  src/shared/consts.tsx
Labels: bug, Done

#1058 fix: M2-3735 Cannot save Applet with Activity with Slider, Slider Row Item, if label(s) text length is more than expected characters
  src/modules/Builder/features/ActivityFlowAbout/ActivityFlowAbout.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SliderRows/SliderPanel/SliderPanel.tsx
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.schema.ts
Labels: Done

#1059 fix: M2-3734 Fix select arrow position in Single/Multiple Selection per Row Item
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SelectionRows/Header/Header.styles.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SelectionRows/Header/Header.tsx
Labels: Done

#1063 fix: M2-3743 Report Configuration. Some characters are cut off in "Send Report(s) to:" input
  src/shared/components/FormComponents/TagsController/TagsController.styles.ts
  src/shared/components/FormComponents/TagsController/TagsController.tsx
Labels: bug, Done

#1061 fix: M2-3742 Date picker button is disabled in “Review Date” field on the “Review” tab (DataViz)
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/ReviewMenu/ReviewMenu.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ReportFilters/ReportFilters.tsx
  src/shared/components/DatePicker/DatePicker.tsx
  src/shared/components/DatePicker/DatePicker.types.ts
  src/shared/hooks/useTable.ts
Labels: bug, Done

#1064 fix: M2-3753 Error 422 is occurred in case user hasn't changed manually access activity time in fields "From" and "To"
  src/modules/Dashboard/features/Applet/Schedule/EventForm/AvailabilityTab/AvailabilityTab.styles.ts
  src/modules/Dashboard/features/Applet/Schedule/EventForm/AvailabilityTab/AvailabilityTab.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.utils.tsx
  src/shared/components/ButtonWithMenu/ButtonWithMenu.styles.ts
  src/shared/styles/theme.ts
  src/shared/styles/variables/palette.ts
Labels: bug, Done

#1065 feat: M2-3705 Write unit tests for some shared functions (builderHelpers.ts, dateTimezone.ts)
  src/shared/utils/builderHelpers.test.ts
  src/shared/utils/dateTimezone.test.ts
  src/shared/utils/dateTimezone.ts
  src/shared/utils/errors.ts
  src/shared/utils/getApiError.ts
  src/shared/utils/index.ts
  src/shared/utils/state.ts
Labels: Done

#1069 feat: M2-3775 Unit tests for useAsync hook
  src/shared/hooks/useAsync.test.ts
Labels: Done

#1075 feat: M2-3749 Add Banner to all pages
  src/modules/Auth/layouts/AuthLayout/AuthLayout.styles.ts
  src/modules/Auth/layouts/AuthLayout/AuthLayout.tsx
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/components/Banner/Banner.const.ts
  src/shared/components/Banner/Banner.styles.ts
  src/shared/components/Banner/Banner.tsx
  src/shared/components/Banner/index.ts
  src/shared/components/index.ts
  src/shared/layouts/BaseLayout/components/TopBar/TopBar.tsx
  src/shared/styles/styledComponents/Buttons.ts
  src/svgSprite.ts
Labels: Done

#1085 fix: M2-3857 If item is the part of a condition, it cannot be hidden and unhide if it was hidden before
  src/modules/Builder/components/ConditionRow/ConditionRow.tsx
  src/modules/Builder/features/ActivityItems/ActivityItems.utils.ts
  src/modules/Builder/features/ActivityItems/LeftBar/Item/Item.tsx
  src/modules/Builder/features/ActivityItemsFlow/ItemFlow/SummaryRow/SummaryRow.tsx
Labels: bug, Done

#1086 feat: M2-3880 Add Support link to the footer, replace the link value for Credits
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/components/Footer/Footer.const.ts
  src/shared/components/Footer/Footer.tsx
Labels: Done

#1087 fix: M2-3632 Activity Flow Settings. Impossible to deselect and save Item Value checkbox
  src/modules/Builder/features/Activities/Activities.tsx
  src/modules/Builder/features/ActivityFlowBuilder/ActivityFlowBuilder.tsx
  src/modules/Builder/features/ActivityFlowBuilder/ActivityFlowBuilder.types.ts
  src/modules/Builder/features/ActivityFlowBuilder/ActivityFlowBuilder.utils.tsx
  src/modules/Builder/features/ActivityItems/DeleteItemModal/DeleteItemModal.tsx
  src/modules/Builder/types/Builder.types.ts
  src/shared/components/Banner/Banner.styles.ts
  src/shared/components/Banner/Banner.tsx
  src/shared/features/AppletSettings/ReportConfigSetting/ReportConfigSetting.tsx
  src/shared/features/AppletSettings/ReportConfigSetting/ReportConfigSetting.utils.ts
Labels: bug, Done

#1092 fix: M2-3884 "Invalid data format" alert is displayed when user imports individual plan of the other respondent
  src/shared/components/FileUploader/FileUploader.utils.tsx
Labels: bug, Done

#1096 fix: M2-3894 Update Menu position for item in Activity Flow Builder
  src/shared/utils/shouldForwardProp.ts
Labels: bug, Done

#1100 tests: M2-3874 Unit tests for Image Uploader component
  src/shared/components/Uploader/ActionButtons/ActionButtons.tsx
  src/shared/components/Uploader/Uploader.test.tsx
  src/shared/components/Uploader/Uploader.tsx
Labels: Done, tests

#1103 fix: M2-3905 activities are duplicated if user imports from the library to existed applet
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.tsx
Labels: bug, Done

#1110 M2-3902 Select respondents popup
  src/modules/Dashboard/features/Managers/Popups/SelectRespondentsPopup/SelectRespondents/Select/Select.tsx
  src/modules/Dashboard/features/Managers/Popups/SelectRespondentsPopup/SelectRespondents/Select/Select.types.ts
  src/modules/Dashboard/features/Managers/Popups/SelectRespondentsPopup/SelectRespondents/SelectRespondents.tsx
  src/modules/Dashboard/features/Managers/Popups/SelectRespondentsPopup/SelectRespondentsPopup.test.tsx
  src/shared/mock.ts
Labels: tests

#1115 fix: M2-3898 Report Configuration in Applet Editing Settings don't change values after save
  src/shared/features/AppletSettings/ReportConfigSetting/ReportConfigSetting.tsx
Labels: bug, Done
