Repository ChildMindInstitute/mindlogger-admin, pull requests merged in 2023-11, with the labels that each got.

#1113 M2-3924 Dashboard table
  src/modules/Dashboard/components/DashboardTable/DashboardTable.test.tsx
  src/modules/Dashboard/components/DashboardTable/DashboardTable.tsx
Labels: tests

#1121 M2-3926: dashboard applet settings
  src/modules/Dashboard/features/Applet/DashboardAppletSettings/DashboardAppletSettings.test.tsx
  src/modules/Dashboard/features/Applet/DashboardAppletSettings/DashboardAppletSettings.tsx
  src/modules/Dashboard/features/Applet/DashboardAppletSettings/DashboardAppletSettings.utils.test.tsx
  src/shared/components/NavigationMenu/NavigationMenu.tsx
  src/shared/components/NavigationMenu/NavigationMenu.types.ts
  src/shared/features/AppletSettings/AppletSettings.tsx
  src/shared/features/AppletSettings/AppletSettings.types.ts
Labels: tests

#1134 tests: M2-3959 AppletsTable
  src/modules/Dashboard/features/Applets/AppletsTable/AppletsTable.test.tsx
Labels: tests

#1137 [DON'T MERGE until prod release] fix: M2-4013 Edit Respondent Popup: Nickname field is not required
  src/modules/Dashboard/api/api.types.ts
  src/modules/Dashboard/features/Respondents/Popups/EditRespondentPopup/EditRespondentPopup.schema.ts
  src/modules/Dashboard/features/Respondents/Popups/EditRespondentPopup/EditRespondentPopup.tsx
  src/modules/Dashboard/features/Respondents/Popups/EditRespondentPopup/EditRespondentPopup.types.ts
Labels: bug, done

#1144 fix: M2-4032 It is not possible to click Review on the context menu after hovering the response dot
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/BarChart/BarChart.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/BarChart/ChartTooltip/ChartTooltip.styles.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/Chart.styles.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/Chart.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/Charts.const.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/Charts.utils.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/LineChart/SubscaleLineChart/ChartTooltip/ChartTooltip.styles.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/LineChart/SubscaleLineChart/ChartTooltip/ChartTooltip.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/LineChart/SubscaleLineChart/SubscaleLineChart.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/LineChart/TimePickerLineChart/ChartTooltip/ChartTooltip.styles.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/LineChart/TimePickerLineChart/ChartTooltip/ChartTooltip.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/LineChart/TimePickerLineChart/TimePickerLineChart.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/MultiScatterChart/ChartTooltip/ChartTooltip.styles.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/MultiScatterChart/ChartTooltip/ChartTooltip.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/MultiScatterChart/MultiScatterChart.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/ScatterChart/ChartTooltip/ChartTooltip.styles.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/ScatterChart/ChartTooltip/ChartTooltip.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/ScatterChart/ScatterChart.const.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/ScatterChart/ScatterChart.styles.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/ScatterChart/ScatterChart.tsx
Labels: bug, done

#1147 fix: M2-4009 Dashboard/Respondents: There is empty record in the 'Nickname' column when first name/last name is not specified
  src/modules/Dashboard/features/Respondents/Respondents.tsx
  src/shared/utils/joinWihComma.ts
Labels: bug, done

#1132 [DON'T MERGE until prod release] feat: M2-3989 Remove disabling the serializable check for redux-toolkit global store and fix browser console errors, fix redux store types
  src/modules/Auth/features/ResetPassword/ResetForm/ResetForm.tsx
  src/modules/Auth/features/SignUp/SignUpForm/SignUpForm.tsx
  src/modules/Auth/state/Auth.reducer.ts
  src/modules/Auth/state/Auth.thunk.ts
  src/modules/Auth/state/Auth.utils.ts
  src/modules/Builder/state/Themes/Themes.thunk.ts
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.hooks.ts
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.types.ts
  src/modules/Dashboard/features/Applet/DashboardAppletSettings/DashboardAppletSettings.test.tsx
  src/modules/Dashboard/state/Applets/Applets.thunk.ts
  src/modules/Dashboard/state/Users/Users.thunk.ts
  src/modules/Library/state/Library.thunk.ts
  src/redux/store/reducers.ts
  src/redux/store/store.ts
  src/shared/components/Error/Error.types.ts
  src/shared/hooks/useAsync.ts
  src/shared/hooks/useCheckIfAppletHasNotFoundError.ts
  src/shared/state/Alerts/Alerts.reducer.ts
  src/shared/state/Alerts/Alerts.thunk.ts
  src/shared/state/Applet/Applet.thunk.ts
  src/shared/state/Base/Base.schema.ts
  src/shared/state/Workspaces/Workspaces.reducer.ts
  src/shared/state/Workspaces/Workspaces.thunk.ts
  src/shared/utils/errors.ts
  src/shared/utils/state.ts
Labels: done, TODOs

#1136 tests: M2-3993 ScoreAndReports utils
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoresAndReports.utils.test.ts
  src/shared/mock.ts
Labels: tests

#1133 tests: M2-3958 AppletItem
  src/modules/Dashboard/features/Applets/AppletsTable/AppletItem/AppletItem.test.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/AppletItem/AppletItem.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/AppletItem/AppletItem.utils.tsx
Labels: tests

#1150 feat: M2-4051 Make Activity Item Setting closed on the backdrop click (click outside the Settings panel).
  src/modules/Builder/features/ActivityItems/ItemConfiguration/Settings/ItemSettingsDrawer/ItemSettingsDrawer.styles.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/Settings/ItemSettingsDrawer/ItemSettingsDrawer.tsx
Labels: enhancement, done

#1131 Tests/m2 3981 url generator
  src/shared/utils/urlGenerator.test.ts
  src/shared/utils/urlGenerator.ts
Labels: tests

#1126 feat/3964-library-components-tests
  src/modules/Library/components/Header/Header.test.tsx
  src/modules/Library/features/Applet/Popups/RemoveAppletPopup/RemoveAppletPopup.test.tsx
  src/modules/Library/features/Popups/AuthPopup/AuthPopup.test.tsx
  src/modules/Library/utils/dataFromStorage.test.ts
  src/modules/Library/utils/getCheckedItems.test.ts
  src/modules/Library/utils/getCheckedItems.ts
  src/redux/store/reducers.ts
  src/shared/utils/renderWithProviders.tsx
Labels: tests

#1145 M2-4003: Unit tests for report utils (compareActivityItem, formatActivityItemAnswers)
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.utils.test.ts
  src/shared/mock.ts
Labels: tests

#1155 M2-4043 AppletPassword popup
  src/modules/Dashboard/features/Applet/Popups/AppletPasswordPopup/AppletPasswordPopup.test.tsx
  src/shared/components/Modal/Modal.tsx
  src/shared/components/Spinner/Spinner.tsx
Labels: tests

#1157 M2-4064: Add preloader on calendar event(s) create/update/delete/import, fix issues
  src/modules/Dashboard/features/Applet/Schedule/AddIndividualSchedulePopup/AddIndividualSchedulePopup.tsx
  src/modules/Dashboard/features/Applet/Schedule/AddIndividualSchedulePopup/AddIndividualSchedulePopup.types.ts
  src/modules/Dashboard/features/Applet/Schedule/ClearScheduledEventsPopup/ClearScheduledEventsPopup.tsx
  src/modules/Dashboard/features/Applet/Schedule/ConfirmScheduledAccessPopup/ConfirmScheduledAccess.types.ts
  src/modules/Dashboard/features/Applet/Schedule/ConfirmScheduledAccessPopup/ConfirmScheduledAccessPopup.tsx
  src/modules/Dashboard/features/Applet/Schedule/CreateEventPopup/CreateEventPopup.tsx
  src/modules/Dashboard/features/Applet/Schedule/EditEventPopup/EditEventPopup.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/AvailabilityTab/AvailabilityTab.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.types.ts
  src/modules/Dashboard/features/Applet/Schedule/EventForm/NotificationsTab/NotificationsTab.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/TimersTab/TimersTab.tsx
  src/modules/Dashboard/features/Applet/Schedule/ImportSchedulePopup/ImportSchedulePopup.tsx
  src/modules/Dashboard/features/Applet/Schedule/Legend/SearchPopup/SearchPopup.tsx
  src/modules/Dashboard/features/Applet/Schedule/RemoveAllScheduledEventsPopup/RemoveAllScheduledEventsPopup.tsx
  src/modules/Dashboard/features/Applet/Schedule/RemoveAllScheduledEventsPopup/RemoveAllScheduledEventsPopup.types.ts
  src/modules/Dashboard/features/Applet/Schedule/RemoveIndividualSchedulePopup/RemoveIndividualSchedulePopup.tsx
  src/modules/Dashboard/features/Applet/Schedule/RemoveScheduledEventPopup/RemoveScheduledEventPopup.tsx
  src/modules/Dashboard/features/Applet/Schedule/RemoveScheduledEventPopup/RemoveScheduledEventPopup.types.ts
  src/shared/components/TimePicker/TimePicker.styles.ts
Labels: done

#1153 tests: m2-4005 applets component
  src/modules/Dashboard/features/Applets/Applets.test.tsx
  src/modules/Dashboard/features/Applets/Applets.tsx
  src/modules/Dashboard/features/Respondents/Respondents.test.tsx
Labels: tests

#1171 Fix/m2 1276 manual input is not allowed in input type number
  src/modules/Builder/components/ToggleItemContainer/ToggleItemContainer.styles.ts
  src/modules/Builder/consts.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/Alerts/Alert/Alert.const.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/Alerts/Alert/Alert.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/Alerts/Alert/Alert.utils.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/AudioRecord/AudioRecord.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/NumberSelection/NumberSelection.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SliderRows/SliderPanel/ScoreCell/ScoreCell.styles.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SliderRows/SliderPanel/ScoreCell/ScoreCell.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SliderRows/SliderPanel/SliderPanel.const.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SliderRows/SliderPanel/SliderPanel.styles.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SliderRows/SliderPanel/SliderPanel.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SliderRows/SliderPanel/SliderPanel.utils.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SliderRows/SliderRows.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/TextResponse/TextResponse.styles.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/TextResponse/TextResponse.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ItemConfiguration.const.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ItemConfiguration.utils.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/Settings/ItemSettingsController/ItemSettingsGroup/ItemSettingsGroup.tsx
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.schema.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
  src/modules/Builder/utils/getDefaultSliderScores.ts
  src/modules/Builder/utils/index.ts
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/components/FormComponents/InputController/Input/Input.const.ts
  src/shared/components/FormComponents/InputController/Input/Input.styles.ts
  src/shared/components/FormComponents/InputController/Input/Input.tsx
  src/shared/components/FormComponents/InputController/InputController.types.ts
  src/shared/components/FormComponents/SelectController/SelectController.tsx
  src/shared/components/FormComponents/SelectController/SelectController.types.ts
Labels: bug, done

#1174 M2-4063: Section score common fields
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.utils.test.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionScoreCommonFields/SectionScoreCommonFields.test.tsx
  src/modules/Library/features/Cart/Cart.tsx
  src/shared/mock.ts
Labels: tests

#1185 M2-4166: Fix Input type number behavior if minNumberValue property is zero
  src/shared/components/FormComponents/InputController/Input/Input.tsx
Labels: bug

#1186 M2-4166: Fix Input type number behavior if minNumberValue property is zero
  src/shared/components/FormComponents/InputController/Input/Input.tsx
Labels: bug

#1180 M2-4079: Media uploader unit tests
  src/modules/Builder/components/MediaUploader/MediaUploader.test.tsx
  src/modules/Builder/components/MediaUploader/MediaUploader.tsx
Labels: tests

#1190 M2-4131: Mixpanel performance task
  src/modules/Builder/features/Activities/Activities.tsx
  src/modules/Builder/features/Activities/ActivitiesHeader/ActivitiesHeader.tsx
Labels: bug

#1191 M2-4174: A positive integer is required in Number Selection item
  package.json
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.schema.ts
  src/resources/app-en.json
  src/resources/app-fr.json
Labels: bug, done

#1192 M2-4174: A positive integer is required in Number Selection item
  package.json
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.schema.ts
  src/resources/app-en.json
  src/resources/app-fr.json
Labels: release bug

#1196 M2-4173: fixed items in scores and reports in duplicated activity
  package-lock.json
  package.json
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
  src/modules/Builder/types/Builder.types.ts
Labels: release bug

#1199 M2-4179: Empty range of scores
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.tsx
Labels: bug

#1204 M2-4200: fixed try-catch handler for export data modal
  src/modules/Dashboard/features/Respondents/Popups/DataExportPopup/DataExportPopup.tsx
  src/modules/Dashboard/hooks/useDecryptedActivityData.ts
  src/shared/components/ErrorFallback/ErrorFallback.tsx
  src/shared/utils/exportData/prepareData.ts
  src/shared/utils/logger.ts
Labels: bug

#1205 M2-4200: fixed try-catch handler for export data modal
  src/modules/Dashboard/features/Respondents/Popups/DataExportPopup/DataExportPopup.tsx
  src/modules/Dashboard/hooks/useDecryptedActivityData.ts
  src/shared/components/ErrorFallback/ErrorFallback.tsx
  src/shared/utils/exportData/prepareData.ts
  src/shared/utils/logger.ts
Labels: release bug

#1202 M2-4158: added cross-day validation for notifications and reminders
  src/modules/Dashboard/features/Applet/Schedule/EventForm/AvailabilityTab/AvailabilityTab.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.hooks.ts
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.schema.ts
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.types.ts
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.utils.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/NotificationsTab/Notification/Notification.tsx
  src/modules/Dashboard/state/CalendarEvents/CalendarEvents.schema.ts
Labels: enhancement

#1208 M2-4160: updated validation for Import Schedule .csv
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.utils.tsx
  src/modules/Dashboard/features/Applet/Schedule/ImportSchedulePopup/ImportSchedulePopup.utils.tsx
  src/resources/app-en.json
  src/resources/app-fr.json
Labels: enhancement

#1211 Feature/M2-4161: Displaying the cross-day event in the Calendar
  src/modules/Dashboard/features/Applet/Schedule/Calendar/Calendar.const.ts
  src/modules/Dashboard/features/Applet/Schedule/Calendar/Calendar.tsx
  src/modules/Dashboard/features/Applet/Schedule/Calendar/Event/Event.tsx
  src/modules/Dashboard/features/Applet/Schedule/Calendar/EventContainerWrapper/EventContainerWrapper.tsx
  src/modules/Dashboard/features/Applet/Schedule/Calendar/EventWrapper/EventWrapper.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/AvailabilityTab/AvailabilityTab.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.hooks.ts
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.utils.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/NotificationsTab/Reminder/Reminder.tsx
  src/modules/Dashboard/features/Applet/Schedule/Schedule.hooks.ts
  src/modules/Dashboard/features/Applet/Schedule/Schedule.utils.tsx
  src/modules/Dashboard/state/CalendarEvents/CalendarEvents.schema.ts
  src/modules/Dashboard/state/CalendarEvents/CalendarEvents.utils.ts
  src/shared/components/Tooltip/Tooltip.types.ts
Labels: enhancement, done

#1215 Tests/M2-4218-coverage-for-cross-day-validation
  src/modules/Dashboard/features/Applet/AddUser/InvitationsTable/InvitationsTable.test.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.utils.test.ts
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.utils.tsx
Labels: tests

#1206 M2-4155: Clear scheduled events popup tests
  src/modules/Dashboard/features/Applet/Schedule/ClearScheduledEventsPopup/ClearScheduledEventsPopup.test.tsx
  src/modules/Dashboard/features/Applet/Schedule/ClearScheduledEventsPopup/ClearScheduledEventsPopup.tsx
Labels: tests

#1219 M2-4205: Score Content tests
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/CopyId/CopyId.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.test.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.tsx
  src/shared/components/DataTable/DataTable.tsx
  src/shared/mock.ts
Labels: tests

#1227 M2-4230: Cross-day event reminder time validation depending on the activity incomplete field
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.schema.ts
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.types.ts
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.utils.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/NotificationsTab/Reminder/Reminder.tsx
  src/shared/components/FormComponents/InputController/Input/Input.tsx
Labels: enhancement, done

#1228 M2-4144: The loader doubles when saving an event in the calendar
  src/modules/Dashboard/features/Applet/Schedule/CreateEventPopup/CreateEventPopup.tsx
  src/modules/Dashboard/features/Applet/Schedule/EditEventPopup/EditEventPopup.tsx
Labels: bug, done

#1230 M2-4228: Hide "Report Config" from the "Applet Settings" of the Applet page of the Dashboard, and keep it only within the Editing mode (Builder)
  src/modules/Builder/features/ActivityFlowSettings/ActivityFlowSettings.utils.tsx
  src/modules/Builder/features/ActivitySettings/ActivitySettings.utils.tsx
  src/modules/Builder/features/BuilderAppletSettings/BuilderAppletSettings.types.ts
  src/modules/Builder/features/BuilderAppletSettings/BuilderAppletSettings.utils.tsx
  src/modules/Builder/features/ReportConfigSetting/Popups/ErrorPopup/ErrorPopup.tsx
  src/modules/Builder/features/ReportConfigSetting/Popups/ErrorPopup/ErrorPopup.types.ts
  src/modules/Builder/features/ReportConfigSetting/Popups/ErrorPopup/index.ts
  src/modules/Builder/features/ReportConfigSetting/Popups/ServerVerifyErrorPopup/ServerVerifyErrorPopup.tsx
  src/modules/Builder/features/ReportConfigSetting/Popups/ServerVerifyErrorPopup/ServerVerifyErrorPopup.types.ts
  src/modules/Builder/features/ReportConfigSetting/Popups/ServerVerifyErrorPopup/index.ts
  src/modules/Builder/features/ReportConfigSetting/Popups/SuccessPopup/SuccessPopup.tsx
  src/modules/Builder/features/ReportConfigSetting/Popups/SuccessPopup/SuccessPopup.types.ts
  src/modules/Builder/features/ReportConfigSetting/Popups/SuccessPopup/index.ts
  src/modules/Builder/features/ReportConfigSetting/Popups/WarningPopup/WarningPopup.tsx
  src/modules/Builder/features/ReportConfigSetting/Popups/WarningPopup/WarningPopup.types.ts
  src/modules/Builder/features/ReportConfigSetting/Popups/WarningPopup/index.ts
  src/modules/Builder/features/ReportConfigSetting/Popups/index.ts
  src/modules/Builder/features/ReportConfigSetting/ReportConfigSetting.const.ts
  src/modules/Builder/features/ReportConfigSetting/ReportConfigSetting.hooks.ts
  src/modules/Builder/features/ReportConfigSetting/ReportConfigSetting.schema.ts
  src/modules/Builder/features/ReportConfigSetting/ReportConfigSetting.styles.ts
  src/modules/Builder/features/ReportConfigSetting/ReportConfigSetting.tsx
  src/modules/Builder/features/ReportConfigSetting/ReportConfigSetting.types.ts
  src/modules/Builder/features/ReportConfigSetting/ReportConfigSetting.utils.ts
  src/modules/Builder/features/ReportConfigSetting/ServerNotConfigured/ServerNotConfigured.tsx
  src/modules/Builder/features/ReportConfigSetting/ServerNotConfigured/ServerNotConfigured.types.ts
  src/modules/Builder/features/ReportConfigSetting/ServerNotConfigured/index.ts
  src/modules/Builder/features/ReportConfigSetting/index.ts
  src/modules/Dashboard/features/Applet/DashboardAppletSettings/DashboardAppletSettings.utils.tsx
  src/shared/components/FormComponents/EditorController/EditorController.styles.ts
  src/shared/components/FormComponents/EditorController/EditorController.tsx
  src/shared/components/FormComponents/TagsController/TagsController.styles.ts
  src/shared/components/MarkDownEditor/CharacterCounter/CharacterCounter.tsx
  src/shared/components/MarkDownEditor/CharacterCounter/CharacterCounter.types.ts
  src/shared/features/AppletSettings/index.ts
Labels: enhancement

#1239 M2-4259: Calendar Event editing - save button is disabled if only activity incomplete field is changed
  src/modules/Dashboard/features/Applet/Schedule/EventForm/NotificationsTab/Reminder/Reminder.tsx
Labels: bug, done

#1243 M2-4257: Can't remove item with Reports Section conditional logic, Reports Section conditions aren't cleared from items that have been removed.
  src/modules/Builder/features/ActivityItems/DeleteItemModal/DeleteItemModal.tsx
Labels: bug, done

#1244 Fix/M2-4242-media-items-are-not-exported
  package.json
  src/shared/types/answer.ts
  src/shared/utils/exportData/getUrls.ts
  src/shared/utils/exportData/parseResponseValue.ts
Labels: release bug
