Repository ChildMindInstitute/mindlogger-admin, pull requests merged in 2023-09, with the labels that each got.

#865 fix: M2-3200 Show more than 20 applets on Respondents/Managers tab. Refactored Tables.
  src/modules/Dashboard/components/DashboardTable/DashboardTable.styles.ts
  src/modules/Dashboard/components/DashboardTable/DashboardTable.tsx
  src/modules/Dashboard/components/DashboardTable/DashboardTable.types.ts
  src/modules/Dashboard/components/DashboardTable/index.tsx
  src/modules/Dashboard/components/Table/index.tsx
  src/modules/Dashboard/components/index.ts
  src/modules/Dashboard/features/Applet/AddUser/InvitationsTable/InvitationsTable.tsx
  src/modules/Dashboard/features/Applets/Applets.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/AppletItem/AppletItem.styles.ts
  src/modules/Dashboard/features/Applets/AppletsTable/AppletItem/AppletItem.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/AppletItem/AppletItem.types.ts
  src/modules/Dashboard/features/Applets/AppletsTable/AppletItem/AppletItem.utils.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/AppletItem/index.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/AppletsTable.hooks.ts
  src/modules/Dashboard/features/Applets/AppletsTable/AppletsTable.styles.ts
  src/modules/Dashboard/features/Applets/AppletsTable/AppletsTable.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/AppletsTable.types.ts
  src/modules/Dashboard/features/Applets/AppletsTable/FolderItem/FolderItem.const.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/FolderItem/FolderItem.styles.ts
  src/modules/Dashboard/features/Applets/AppletsTable/FolderItem/FolderItem.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/FolderItem/FolderItem.types.ts
  src/modules/Dashboard/features/Applets/AppletsTable/FolderItem/index.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/index.tsx
  src/modules/Dashboard/features/Applets/Table/Table.types.ts
  src/modules/Dashboard/features/Applets/Table/index.tsx
  src/modules/Dashboard/features/Managers/Managers.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ReportTable/ReportTable.tsx
  src/modules/Dashboard/features/Respondents/Respondents.tsx
  src/shared/components/Table/Table.const.ts
  src/shared/components/Table/Table.tsx
Labels: bug, Done

#869 fix: M2-3124 Report Configuration. Item Value checkbox is not saving after Save and Publish.
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.utils.ts
  src/modules/Builder/hooks/useCurrentActivityFlow.ts
  src/modules/Builder/state/ReportConfig/ReportConfig.reducer.ts
  src/shared/features/AppletSettings/ReportConfigSetting/ReportConfigSetting.tsx
Labels: bug, Done

#874 fix: M2-3189 "Builder" appears in breadcrumbs in Editing mode.
  src/shared/hooks/useBreadcrumbs.tsx
Labels: enhancement, Done

#873 fix: M2-3273 Section Conditional Logic is not duplicated after duplicate activity.
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoresAndReports.tsx
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
Labels: bug, Done

#878 fix: M2-2803 Text alignment feature doesn't work.
  src/shared/components/MarkDownEditor/MarkDownEditor.const.ts
  src/shared/components/MarkDownEditor/MarkDownEditor.utils.ts
  src/shared/components/MarkDownEditor/extensions/AlignTextExtension/AlignTextExtension.tsx
Labels: bug

#876 fix: M2-3288 Report Configuration. Subject Preview is not changing if Item Value selected.
  src/shared/features/AppletSettings/ReportConfigSetting/ReportConfigSetting.hooks.ts
  src/shared/features/AppletSettings/ReportConfigSetting/ReportConfigSetting.tsx
  src/shared/features/AppletSettings/ReportConfigSetting/ReportConfigSetting.types.ts
  src/shared/features/AppletSettings/ReportConfigSetting/ReportConfigSetting.utils.ts
Labels: bug, Done

#881 fix: M2-3060 Preview for the video files in mp4 format added to Displayed Content section aren't displayed.
  src/shared/components/MarkDownEditor/MarkDownEditor.const.ts
Labels: bug, Done

#883 fix: M2-2781 Scores & Reports. Score Conditions. Error messages are cut off on collapsed section.
  src/modules/Builder/components/ToggleItemContainer/ToggleItemContainer.styles.ts
Labels: bug, Done

#886 fix: M2-3054 The time on the right side of the progress bar increases as the mp3 is played when playing recorded audio.
  src/modules/Builder/components/MLPlayer/MLPlayer.const.ts
  src/modules/Builder/components/MLPlayer/MLPlayer.hooks.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/AudioPlayer/AudioPlayer.tsx
Labels: bug, Done

#890 fix: M2-3306 Scores and Reports. Score conditional logic conditions are not changed after update the score id. Score conditional logic conditions remove issue.
  src/modules/Builder/components/ConditionRow/ConditionRow.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ConditionContent/ConditionContent.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ConditionContent/ConditionContent.utils.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.utils.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
  src/shared/state/Applet/Applet.schema.ts
Labels: Done

#895 Fix/m2 3316 wrong index in abtrails response in activity user journey
  src/shared/utils/exportData/prepareData.ts
Labels: bug

#896 feat: M2-3068 Set max width for Activity Cards, Item Cards, and Header/actions row.
  src/modules/Builder/features/Activities/Activities.tsx
  src/modules/Builder/features/ActivityFlow/ActivityFlow.tsx
  src/modules/Builder/features/ActivityFlowBuilder/ActivityFlowBuilder.tsx
  src/modules/Builder/features/ActivityItems/LeftBar/LeftBar.tsx
  src/modules/Builder/features/ActivityItemsFlow/ActivityItemsFlow.tsx
  src/modules/Dashboard/features/Applets/Applets.tsx
  src/shared/styles/styledComponents/Builder.ts
Labels: enhancement, Done

#898 feat: M2-3101 The Alerts list needs to be refreshed after deleting the related Applet.
  src/modules/Dashboard/components/DashboardTable/DashboardTable.tsx
  src/modules/Dashboard/features/Applet/Popups/DeletePopup/DeletePopup.tsx
  src/modules/Dashboard/features/Applets/Applets.hooks.ts
  src/modules/Dashboard/features/Applets/AppletsTable/AppletsTable.tsx
  src/modules/Dashboard/features/Managers/Managers.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ReportTable/ReportTable.tsx
  src/modules/Dashboard/features/Respondents/Respondents.tsx
  src/shared/components/Table/Table.const.ts
  src/shared/components/Table/Table.tsx
  src/shared/consts.tsx
  src/shared/hooks/useTable.ts
  src/shared/layouts/BaseLayout/BaseLayout.tsx
  src/shared/layouts/BaseLayout/components/TopBar/Notifications/Notifications.hooks.ts
  src/shared/state/Alerts/Alerts.const.ts
Labels: Done

#905 Fix/m2 3311 fix long media files names
  src/shared/utils/exportData/getReportName.ts
  src/shared/utils/exportData/prepareData.ts
Labels: bug

#903 fix: M2-3373 Error on duplicating an Activity while creating an Applet.
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoresAndReports.tsx
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
Labels: bug, Done

#902 fix: M2-3326 Android. Application crashes on Item with audio added to Displayed Content section.
  src/shared/components/MarkDownEditor/MarkDownEditor.const.ts
  src/shared/components/MarkDownEditor/MarkDownEditor.utils.ts
  src/shared/components/MarkDownEditor/extensions/AudioUploadExtension/AudioUploadExtension.tsx
Labels: bug, Done

#908 feat: M2-3041 Replace hardcoded picture avatar (dog) with the User's initials avatar.
  src/assets/images/avatar.png
  src/modules/Auth/features/Login/LockForm/LockForm.tsx
  src/modules/Auth/features/Login/Login.styles.ts
  src/modules/Auth/state/index.ts
  src/shared/components/Avatar/Avatar.styles.ts
  src/shared/components/Avatar/Avatar.tsx
  src/shared/components/Avatar/Avatar.types.ts
  src/shared/components/Avatar/index.ts
  src/shared/components/index.ts
  src/shared/layouts/BaseLayout/components/TopBar/AccountPanel/AccountPanel.styles.ts
  src/shared/layouts/BaseLayout/components/TopBar/AccountPanel/AccountPanel.tsx
  src/shared/layouts/BaseLayout/components/TopBar/TopBar.styles.ts
  src/shared/layouts/BaseLayout/components/TopBar/TopBar.tsx
Labels: enhancement, Done

#917 fix: M2-3408 Scores & Reports. Impossible to add score
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.utils.ts
  src/shared/components/DataTable/DataTable.tsx
Labels: bug, Done

#916 feat: M2-3376 Sanitize fields from Cross-site scripting (XSS) vulnerabilities and HTML injection. Prohibit to use of links as applet names.
  package-lock.json
  package.json
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.hooks.ts
  src/shared/components/FormComponents/EditorController/EditorController.tsx
  src/shared/consts.tsx
  src/shared/features/AppletSettings/ReportConfigSetting/ReportConfigSetting.tsx
  src/shared/utils/forms.ts
Labels: enhancement, Done

#928 fix: M2-1276 Items: manual input is not allowed in input fields with arrows
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SelectionRows/CharactersCounter/CharactersCounter.styles.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SliderRows/SliderPanel/SliderPanel.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SliderRows/SliderPanel/SliderPanel.types.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SliderRows/SliderPanel/SliderPanel.utils.tsx
  src/shared/components/FormComponents/InputController/Input/Input.const.ts
  src/shared/components/FormComponents/InputController/Input/Input.styles.ts
  src/shared/components/FormComponents/InputController/Input/Input.tsx
  src/shared/components/FormComponents/InputController/Input/Input.types.ts
  src/shared/components/FormComponents/InputController/Input/Input.utils.tsx
  src/shared/components/FormComponents/InputController/Input/index.ts
  src/shared/components/FormComponents/InputController/InputController.tsx
  src/shared/components/FormComponents/InputController/InputController.types.ts
  src/shared/components/FormComponents/SelectController/SelectController.types.ts
Labels: bug, Done

#939 fix: M2-3472 Flanker: Configure badge should be displayed instead of Items badge on flanker builder page
  src/modules/Builder/features/ActivityFlowSettings/ActivityFlowSettings.utils.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ConfigurationHeader/ConfigurationHeader.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/Settings/ItemSettingsDrawer/ItemSettingsDrawer.tsx
  src/modules/Builder/features/ActivitySettings/ActivitySettings.utils.tsx
  src/modules/Builder/features/BuilderAppletSettings/BuilderAppletSettings.utils.tsx
  src/modules/Builder/features/PerformanceTasks/PerformanceTaskHeader/PerformanceTaskHeader.styles.ts
  src/modules/Builder/features/PerformanceTasks/PerformanceTaskHeader/PerformanceTaskHeader.tsx
  src/modules/Dashboard/features/Applet/DashboardAppletSettings/DashboardAppletSettings.utils.tsx
  src/shared/hooks/useBreadcrumbs.tsx
  src/shared/utils/getSettingBreadcrumbs.ts
  src/svgSprite.ts
Labels: bug, Done

#937 feat: M2-3400 Custom Themes Support: Admin Panel part
  src/modules/Builder/api/api.ts
  src/modules/Builder/api/api.types.ts
  src/modules/Builder/api/index.ts
  src/modules/Builder/features/AboutApplet/AboutApplet.const.tsx
  src/modules/Builder/features/AboutApplet/AboutApplet.styles.ts
  src/modules/Builder/features/AboutApplet/AboutApplet.tsx
  src/modules/Builder/features/AboutApplet/AboutApplet.utils.tsx
  src/modules/Builder/features/ActivityAbout/ActivityAbout.tsx
  src/modules/Builder/features/ActivityFlowAbout/ActivityFlowAbout.tsx
  src/modules/Builder/features/PerformanceTasks/NameDescription/NameDescriptionContent/NameDescriptionContent.tsx
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.hooks.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.tsx
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
  src/modules/Builder/state/Themes/Themes.reducer.ts
  src/modules/Builder/state/Themes/Themes.schema.ts
  src/modules/Builder/state/Themes/Themes.state.ts
  src/modules/Builder/state/Themes/Themes.thunk.ts
  src/modules/Builder/state/Themes/index.ts
  src/modules/Builder/state/index.ts
  src/modules/Dashboard/api/api.ts
  src/modules/Dashboard/api/api.types.ts
  src/modules/Dashboard/features/Applet/Schedule/Legend/Legend.tsx
  src/modules/Dashboard/state/Users/Users.const.ts
  src/modules/Dashboard/state/Users/Users.thunk.ts
  src/modules/Library/api/api.const.ts
  src/modules/Library/api/api.ts
  src/modules/Library/features/Popups/AddToBuilderPopup/AddToBuilderPopup.const.ts
  src/modules/Library/features/Popups/AddToBuilderPopup/AddToBuilderPopup.tsx
  src/shared/api/api.types.ts
  src/shared/components/FormComponents/EditorController/EditorController.styles.ts
  src/shared/components/FormComponents/SelectController/SelectController.styles.ts
  src/shared/components/FormComponents/SelectController/SelectController.tsx
  src/shared/components/FormComponents/SelectController/SelectController.types.ts
  src/shared/components/Table/Table.const.ts
  src/shared/components/Table/Table.tsx
  src/shared/consts.tsx
  src/shared/features/AppletSettings/ReportConfigSetting/ReportConfigSetting.tsx
Labels: enhancement, Done

#941 feat: M2-1937 Remove “Matter Lab” from footer
  src/shared/components/Footer/Footer.const.ts
  src/shared/components/Footer/Footer.tsx
Labels: enhancement, Done

#946 fix: M2-906 Applet Page: Applet Settings: Data retention tab: It is possible to enter dot in the period
  src/shared/features/AppletSettings/DataRetentionSetting/DataRetention.tsx
Labels: bug, Done

#947 fix: M2-3439 Flanker_360 applet block sequences are empty
  src/modules/Builder/features/PerformanceTasks/Flanker/GeneralSettings/StimulusScreen/StimulusContent/StimulusContent.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/BlockSequences/BlockSequences.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/BlockSequences/BlockSequencesContent/BlockSequencesContent.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/BlockSequences/BlockSequencesContent/BlockSequencesContent.utils.ts
  src/shared/utils/getUploadedMediaName.ts
Labels: bug, Done

#955 fix: M2-3485 Fix removing items if entering subscales configuration.
  src/modules/Builder/features/ActivitySettings/SubscalesConfiguration/SubscalesConfiguration.hooks.ts
  src/modules/Builder/features/ActivitySettings/SubscalesConfiguration/SubscalesConfiguration.tsx
  src/modules/Builder/features/ActivitySettings/SubscalesConfiguration/SubscalesConfiguration.utils.tsx
Labels: bug, Done

#960 M2-3487 Flanker: Delete button on hover of fixation screen image instead of Edit, M2-3486 Flanker: Image name is not displayed on fixation screen settings
  src/modules/Builder/features/PerformanceTasks/Flanker/GeneralSettings/ButtonsScreen/ButtonsContent/ButtonsContent.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/GeneralSettings/FixationScreen/FixationContent/FixationContent.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/GeneralSettings/StimulusScreen/StimulusContent/StimulusContent.tsx
  src/shared/components/Uploader/ActionButtons/ActionButtons.styles.ts
  src/shared/components/Uploader/ActionButtons/ActionButtons.tsx
  src/shared/components/Uploader/ActionButtons/ActionButtons.types.ts
  src/shared/components/Uploader/ActionButtons/index.ts
  src/shared/components/Uploader/Uploader.styles.ts
  src/shared/components/Uploader/Uploader.tsx
  src/shared/components/Uploader/Uploader.types.ts
Labels: bug, Done

#958 feat: M2-3490 Backend errors (Login, Password recovery)
  src/modules/Auth/features/Login/Login.styles.ts
  src/modules/Auth/features/Login/LoginForm/LoginForm.tsx
  src/modules/Auth/features/ResetPassword/Confirmation/Confirmation.styles.ts
  src/modules/Auth/features/ResetPassword/Confirmation/Confirmation.tsx
  src/modules/Auth/features/ResetPassword/ResetForm/ResetForm.styles.ts
  src/modules/Auth/features/ResetPassword/ResetForm/ResetForm.tsx
  src/modules/Auth/features/SignUp/SignUpForm/SignUpForm.styles.ts
  src/modules/Auth/features/SignUp/SignUpForm/SignUpForm.tsx
  src/modules/Auth/layouts/AuthLayout/AuthLayout.styles.ts
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/consts.tsx
  src/shared/styles/styledComponents/Buttons.ts
  src/shared/styles/styledComponents/ClearedButton.ts
  src/shared/styles/styledComponents/DirectoryUpButton.ts
  src/shared/styles/styledComponents/IconButton.ts
  src/shared/styles/styledComponents/SvgPrimaryColorBtn.ts
  src/shared/styles/styledComponents/index.ts
Labels: Done

#963 fix: M2-3518 Fix activity flow navigation issue
  src/modules/Builder/features/ActivityFlow/ActivityFlow.tsx
  src/modules/Builder/features/ActivityFlow/ActivityFlow.utils.tsx
  src/modules/Builder/features/ActivityFlowBuilder/ActivityFlowBuilder.tsx
  src/modules/Builder/hooks/useActivitiesRedirection.ts
  src/modules/Builder/hooks/useActivityFlowsRedirection.ts
Labels: bug, Done

#959 Feature/m2 2201 collapsing header while scrolling
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ConfigurationHeader/ConfigurationHeader.styles.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ConfigurationHeader/ConfigurationHeader.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/RespondentDataReview.styles.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/RespondentDataReview.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.styles.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.tsx
  src/shared/components/NavigationMenu/Container/Container.styles.ts
  src/shared/components/NavigationMenu/Container/Container.tsx
  src/shared/styles/styledComponents/StickyHeader.ts
  src/shared/styles/styledComponents/Typography.ts
  src/shared/styles/styledComponents/index.ts
  src/shared/styles/stylesConsts.ts
  src/shared/styles/variables/index.ts
Labels: enhancement

#973 fix: M2-2150 Dataviz / Subscales - Bugs with the Legend
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/BarChart/BarChart.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/BarChart/BarChart.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/BarChart/BarChart.utils.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/Chart.styles.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/Chart.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/Charts.const.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/Charts.utils.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/LineChart/SubscaleLineChart/SubscaleLineChart.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/LineChart/SubscaleLineChart/SubscaleLineChart.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/LineChart/SubscaleLineChart/SubscaleLineChart.utils.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Subscales/ActivityCompletionScores/ActivityCompletionScores.styles.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Subscales/ActivityCompletionScores/ActivityCompletionScores.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Subscales/AllScores/AllScores.tsx
Labels: bug, Done

#986 feat: M2-3534 Replace a logo in the Admin panel
  src/modules/Auth/layouts/AuthLayout/AuthLayout.tsx
  src/svgSprite.ts
Labels: bug, Done

#985 fix: M2-3554 TypeError is displayed after setting scores and reports in duplicated applet
  src/modules/Builder/components/ConditionRow/ConditionRow.tsx
  src/modules/Builder/components/ConditionRow/ConditionRow.utils.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ConditionContent/ConditionContent.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ConditionContent/CondtitionContent.const.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreCondition/ScoreCondition.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.utils.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionContent/SectionContent.const.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionContent/SectionContent.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionScoreCommonFields/SectionScoreCommonFields.tsx
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.const.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.schema.ts
Labels: bug, Done

#992 feat: M2-3067 Update cell widths for tables
  src/modules/Dashboard/components/DashboardTable/DashboardTable.styles.ts
  src/modules/Dashboard/components/DashboardTable/DashboardTable.tsx
  src/modules/Dashboard/components/DashboardTable/DashboardTable.types.ts
  src/modules/Dashboard/features/Applets/Applets.const.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/AppletItem/AppletItem.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/AppletsTable.styles.ts
  src/modules/Dashboard/features/Applets/AppletsTable/AppletsTable.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/FolderItem/FolderItem.styles.ts
  src/modules/Dashboard/features/Applets/AppletsTable/FolderItem/FolderItem.tsx
  src/modules/Dashboard/features/Managers/Managers.const.tsx
  src/modules/Dashboard/features/Managers/Managers.tsx
  src/modules/Dashboard/features/Respondents/Respondents.const.tsx
  src/modules/Dashboard/features/Respondents/Respondents.tsx
  src/shared/components/Table/Table.styles.ts
  src/shared/components/Table/TableHead/TableHead.styles.ts
  src/shared/components/Table/TableHead/TableHead.tsx
  src/shared/components/Table/TableHead/TableHead.types.ts
  src/shared/styles/theme.ts
Labels: enhancement, Done

#995 feat: M2-3067 Update cell widths for tables - additional fixes
  src/modules/Dashboard/components/DashboardTable/DashboardTable.styles.ts
  src/shared/components/Table/Table.tsx
  src/shared/components/Table/TableHead/TableHead.styles.ts
  src/shared/styles/styledComponents/AppletImage.ts
Labels: bug, Done

#994 feat: M2-3597 Add "Content-Language" header in the API client
  src/shared/api/api.client.ts
  src/shared/api/api.const.ts
  src/shared/api/api.utils.ts
  src/shared/components/Footer/Language/Language.tsx
  src/shared/components/Footer/Language/Language.types.tsx
Labels: enhancement, Done

#997 fix: M2-939 Add Users: The “Generate Public link” pop-up doesn’t match the design
  src/resources/app-en.json
  src/resources/app-fr.json
Labels: bug, Done

#999 fix: M2-1197 Time Range: Wrong color of Start Time and End Time Placeholders
  src/shared/components/DatePicker/DatePicker.styles.ts
  src/shared/components/TimePicker/TimePicker.styles.ts
Labels: bug, Done

#1000 feat: M2-3611 Changes on the footer
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/components/Footer/Footer.tsx
Labels: enhancement, Done

#1009 feat: M2-1958 Calendar/Import: Show all the errors occurred in the import file as a list
  src/modules/Dashboard/features/Applet/Schedule/ImportSchedulePopup/ImportSchedule.const.tsx
  src/modules/Dashboard/features/Applet/Schedule/ImportSchedulePopup/ImportSchedulePopup.hooks.tsx
  src/modules/Dashboard/features/Applet/Schedule/ImportSchedulePopup/ImportSchedulePopup.types.ts
  src/modules/Dashboard/features/Applet/Schedule/ImportSchedulePopup/ImportSchedulePopup.utils.tsx
Labels: enhancement, Done

#1006 fix: M2-1597 Add error about the applet name is already in use on create/duplicate
  src/modules/Builder/components/Popups/SaveAndPublishProcessPopup/Description/Description.tsx
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.hooks.ts
  src/modules/Dashboard/api/api.ts
  src/modules/Dashboard/api/api.types.ts
  src/modules/Dashboard/features/Applet/Popups/AppletPasswordPopup/AppletPasswordPopup.tsx
  src/modules/Dashboard/features/Applet/Popups/AppletPasswordPopup/AppletPasswordPopup.types.ts
  src/modules/Dashboard/features/Applet/Popups/DuplicatePopups/DuplicatePopups.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/FolderItem/FolderItem.tsx
  src/shared/api/api.ts
  src/shared/api/api.types.ts
Labels: enhancement, Done

#1014 fix: M2-3593 Flanker_360: Fixation ‘-----’ is missing before the stimulus screen, fix performance tasks validation
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/TextResponse/TextResponse.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/BlockSequences/BlockSequencesContent/BlockSequencesContent.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/BlockSequences/BlockSequencesContent/BlockSequencesContent.utils.ts
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.utils.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.const.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.schema.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.tsx
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.types.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.utils.tsx
  src/shared/features/AppletSettings/ReportConfigSetting/ReportConfigSetting.schema.ts
  src/shared/state/Applet/Applet.schema.ts
Labels: bug, Done

#1017 feat: M2-3629 Hide 'Share to Library' button
  src/modules/Builder/features/BuilderAppletSettings/BuilderAppletSettings.utils.tsx
  src/modules/Dashboard/features/Applet/DashboardAppletSettings/DashboardAppletSettings.utils.tsx
  src/modules/Dashboard/features/Applet/Popups/DuplicatePopups/DuplicatePopups.tsx
  src/modules/Dashboard/features/Applet/Popups/DuplicatePopups/DuplicatePopups.types.ts
  src/modules/Dashboard/features/Applets/AppletsTable/AppletItem/AppletItem.utils.tsx
Labels: Done

#1021 fix: M2-3638 Items: the first duplication of item create the new item, but with empty fields
  src/modules/Builder/features/ActivityItems/ActivityItems.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/OptionalItemsAndSettings/OptionalItemsAndSettings.tsx
Labels: bug, Done
