Repository ChildMindInstitute/mindlogger-admin, pull requests merged in 2023-12, with the labels that each got.

#1252 M2-4282: added coverage for sspr&mspr
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SelectionRows/Header/Header.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__tests__/ItemConfigurationSelectionRows.test.tsx
Labels: tests

#1248 M2-4208: Score and reports unit tests
  src/modules/Builder/features/ActivitySettings/ActivitySettings.utils.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoresAndReports.test.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoresAndReports.tsx
Labels: tests

#1256 M2-3997: added coverage for prepare data and getParsedAnswers
  src/modules/Dashboard/features/Applet/AddUser/InvitationsTable/InvitationsTable.test.tsx
  src/shared/mock.ts
  src/shared/types/answer.ts
  src/shared/utils/exportData/prepareData.test.ts
  src/shared/utils/getParsedAnswers.test.ts
Labels: tests

#1258 M2-4289: M2-4290 Popup unit tests
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/RemoveConditionalLogicPopup/RemoveConditionalLogicPopup.test.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ChangeScoreIdPopup/ChangeScoreIdPopup.test.tsx
Labels: tests

#1266 Fix/M2-4307 [Admin panel] It's not possible to delete a row in a Condition in the Item flow
  package-lock.json
  package.json
  src/modules/Builder/features/ActivityItemsFlow/ItemFlow/ItemFlowContent/ItemFlowContent.tsx
Labels: release bug

#1259 M2-4195: Unit tests for create/update Event utils
  package.json
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.types.ts
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.utils.test.ts
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.utils.tsx
  src/modules/Dashboard/state/CalendarEvents/CalendarEvents.utils.test.ts
Labels: tests

#1265 M2-4301: Unit tests for Review Menu
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/ReviewMenu/ReviewMenu.test.tsx
Labels: tests

#1264 M2-4275: M2-4276 About applet and activity tests
  src/modules/Builder/features/AboutApplet/AboutApplet.test.tsx
  src/modules/Builder/features/ActivityAbout/ActivityAbout.test.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoresAndReports.test.tsx
  src/shared/mock.ts
Labels: tests

#1278 M2-4336: updated labels in date range filter
  package.json
  src/shared/features/AppletSettings/ExportDataSetting/ExportDataSetting.tsx
Labels: release bug

#1285 M2-4349: added time support in date range filter
  src/modules/Dashboard/features/Respondents/Popups/DataExportPopup/DataExportPopup.tsx
  src/shared/components/DatePicker/DatePicker.tsx
  src/shared/components/DatePicker/DatePicker.types.ts
  src/shared/consts.tsx
  src/shared/features/AppletSettings/ExportDataSetting/ExportDataSetting.tsx
Labels: release bug

#1279 M2-4206: Unit tests for Condition Content
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ConditionContent/ConditionContent.test.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ConditionContent/ScoreSummaryRow/ScoreSummaryRow.test.tsx
  src/shared/mock.ts
Labels: tests

#1275 M2-4308: Test coverage for Schedule (Calendar) utils
  src/modules/Dashboard/state/CalendarEvents/CalendarEvents.schema.ts
  src/modules/Dashboard/state/CalendarEvents/CalendarEvents.utils.test.ts
  src/modules/Dashboard/state/CalendarEvents/CalendarEvents.utils.ts
Labels: tests

#1274 Tests/m2 4328 coverage for get report and media data get report csv object get journey csv object
  src/shared/mock.ts
  src/shared/utils/exportData/getRawScores.test.ts
  src/shared/utils/exportData/getRawScores.ts
  src/shared/utils/exportData/getReportAndMediaData.test.ts
  src/shared/utils/exportData/getReportAndMediaData.ts
  src/shared/utils/exportData/getReportCSVObject.ts
  src/shared/utils/exportData/getSubscales.test.ts
Labels: tests

#1295 M2-4391: The warning message isn’t deleted if Reminder with invalid Activity incomplete or Reminder time is deleted
  src/modules/Dashboard/features/Applet/Schedule/EventForm/NotificationsTab/Reminder/Reminder.tsx
Labels: bug, done

#1296 M2-4393: It's possible to set Reminder for Weekday cross-day event in next day after To time
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.utils.test.ts
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.utils.tsx
  src/setupTests.ts
Labels: bug, done

#1297 M2-4373: M2-4374: Remove and confirm schedule popups
  src/modules/Dashboard/features/Applet/Schedule/ConfirmScheduledAccessPopup/ConfirmScheduledAccessPopup.test.tsx
  src/modules/Dashboard/features/Applet/Schedule/RemoveAllScheduledEventsPopup/RemoveAllScheduledEventsPopup.test.tsx
  src/modules/Dashboard/features/Applet/Schedule/RemoveIndividualSchedulePopup/RemoveIndividualSchedulePopup.test.tsx
  src/modules/Dashboard/features/Applet/Schedule/RemoveIndividualSchedulePopup/RemoveIndividualSchedulePopup.tsx
  src/modules/Dashboard/features/Applet/Schedule/RemoveScheduledEventPopup/RemoveScheduledEventPopup.test.tsx
Labels: tests

#1301 M2-4376: Calendar Event Reminder validation when no end date is provided
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.const.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.utils.test.ts
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.utils.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/NotificationsTab/Reminder/Reminder.tsx
Labels: bug, done

#1287 M2-4337: M2-4338: ScheduleSetup and ViewData popups unit tests
  src/modules/Dashboard/features/Respondents/Popups/ScheduleSetupPopup/ScheduleSetupPopup.test.tsx
  src/modules/Dashboard/features/Respondents/Popups/ViewDataPopup/ViewDataPopup.test.tsx
  src/shared/mock.ts
Labels: tests

#1316 M2-4442: Implement video link rendering in markdown editor preview mode
  src/shared/components/FormComponents/EditorController/Editor/Editor.types.ts
  src/shared/components/FormComponents/EditorController/Editor/Editor.utils.tsx
  src/shared/components/MarkDownEditor/MarkDownEditor.const.ts
  src/shared/components/MarkDownEditor/MarkDownEditor.utils.ts
  src/shared/utils/forms.ts
Labels: bug, done

#1314 M2-4399 Unit tests for SuccessTransferOwnershipPopup and SuccessSharePopup
  src/modules/Dashboard/features/Applet/Popups/SuccessTransferOwnershipPopup/SuccessTransferOwnershipPopup.test.tsx
  src/modules/Dashboard/features/Applet/Popups/SucessSharePopup/SuccessSharePopup.test.tsx
Labels: tests

#1322 M2-4476: Can't save applet with subscales configured
  package.json
  src/modules/Builder/features/ActivitySettings/SubscalesConfiguration/SubscalesConfiguration.const.ts
Labels: release bug

#1323 M2-4396: fixed infinity scroll in select input
  src/modules/Builder/features/AboutApplet/AboutApplet.const.tsx
  src/modules/Builder/features/AboutApplet/AboutApplet.tsx
  src/modules/Builder/features/AboutApplet/ThemeSelectController/ThemeSelectController.tsx
  src/shared/components/FormComponents/SelectController/SelectController.tsx
  src/shared/components/FormComponents/SelectController/SelectController.types.ts
  src/shared/hooks/useInfinityData.ts
Labels: bug

#1320 M2-4426: M2-4427: Unit tests for AppletNotFoundPopup and IncorrectFilePopup
  src/shared/components/AppletNotFoundPopup/AppletNotFoundPopup.test.tsx
  src/shared/components/IncorrectFilePopup/IncorrectFilePopup.test.tsx
  src/shared/components/IncorrectFilePopup/IncorrectFilePopup.tsx
Labels: tests

#1333 M2-4510: Export settings tests
  src/shared/features/AppletSettings/ExportDataSetting/ExportDataSetting.test.tsx
Labels: tests

#1328 M2-4478: M2-4486: DeleteApplet and VersionHistory settings tests
  src/shared/features/AppletSettings/DeleteAppletSetting/DeleteAppletSetting.test.tsx
  src/shared/features/AppletSettings/DeleteAppletSetting/DeleteAppletSetting.tsx
  src/shared/features/AppletSettings/VersionHistorySetting/VersionHistorySetting.test.tsx
Labels: tests

#1331 M2-4508: The “error” highlight doesn't appear for Secret User ID field if such Secret User ID already exists in this Applet
  src/modules/Dashboard/features/Respondents/Popups/EditRespondentPopup/EditRespondentPopup.tsx
Labels: bug, done

#1334 M2-4513: 'That applet name already exists' error is not displayed on the UI after duplicating (with unit tests)
  src/modules/Dashboard/features/Applet/Popups/DeletePopup/DeletePopup.tsx
  src/modules/Dashboard/features/Applet/Popups/DuplicatePopups/DuplicatePopups.test.tsx
  src/modules/Dashboard/features/Applet/Popups/DuplicatePopups/DuplicatePopups.tsx
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/styles/styledComponents/ErrorText.ts
Labels: enhancement, tests

#1335 M2-4509: M2-4511: Edit applet settings and Data retention popups tests
  src/shared/features/AppletSettings/DataRetentionSetting/Popups/ErrorPopup/ErrorPopup.test.tsx
  src/shared/features/AppletSettings/DataRetentionSetting/Popups/SuccessPopup/SuccessPopup.test.tsx
  src/shared/features/AppletSettings/EditAppletSetting/EditAppletSetting.test.tsx
Labels: tests
