Repository ChildMindInstitute/mindlogger-admin, pull requests merged in 2023-08, with the labels that each got.

#723 fix: M2-1800 Calendar: Always Available event is disappearing in the current year view if schedule another event to the next year
  src/modules/Dashboard/features/Applet/Schedule/Calendar/Calendar.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.utils.tsx
  src/modules/Dashboard/features/Applet/Schedule/Schedule.hooks.ts
  src/modules/Dashboard/state/CalendarEvents/CalendarEvents.reducer.ts
  src/modules/Dashboard/state/CalendarEvents/CalendarEvents.schema.ts
  src/modules/Dashboard/state/CalendarEvents/CalendarEvents.state.ts
  src/modules/Dashboard/state/CalendarEvents/index.ts
Labels: bug, Done

#726 fix: M2-2365 Save & Publish doesn't save the report configuration form
  src/modules/Builder/components/Popups/SaveAndPublishProcessPopup/Description/Description.tsx
  src/modules/Builder/components/Popups/SaveAndPublishProcessPopup/SaveAndPublishProcessPopup.tsx
  src/modules/Builder/components/Popups/SaveAndPublishProcessPopup/SaveAndPublishProcessPopup.types.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionContent/SectionContent.tsx
  src/modules/Builder/features/BuilderAppletSettings/BuilderAppletSettings.utils.tsx
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.hooks.ts
  src/modules/Builder/state/ReportConfig/ReportConfig.reducer.ts
  src/modules/Builder/state/ReportConfig/ReportConfig.schema.ts
  src/modules/Builder/state/ReportConfig/ReportConfig.state.ts
  src/modules/Builder/state/ReportConfig/index.ts
  src/modules/Builder/state/index.ts
  src/modules/Dashboard/features/Applet/DashboardAppletSettings/DashboardAppletSettings.utils.tsx
  src/redux/modules/index.ts
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/consts.tsx
  src/shared/features/AppletSettings/ReportConfigSetting/ReportConfigSetting.tsx
Labels: bug, Done

#728 fix: M2-2869 Save & Publish doesn't save the report configuration form
  src/modules/Builder/features/ActivityFlowBuilder/ActivityFlowBuilder.tsx
Labels: bug, Done

#732 Feature/m2 2441 alerts connect to api
  package-lock.json
  package.json
  src/App.tsx
  src/assets/images/logo.png
  src/modules/Auth/state/Auth.reducer.ts
  src/modules/Auth/state/Auth.schema.ts
  src/modules/Auth/state/Auth.thunk.ts
  src/modules/Auth/state/Auth.utils.ts
  src/modules/Dashboard/api/api.ts
  src/modules/Dashboard/api/api.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/ReportMenu/ReportMenu.tsx
  src/modules/Dashboard/routes/routes.tsx
  src/modules/Dashboard/state/Account/Account.reducer.ts
  src/modules/Dashboard/state/Account/Account.schema.ts
  src/modules/Dashboard/state/Account/Account.state.ts
  src/modules/Dashboard/state/Account/Account.thunk.ts
  src/modules/Dashboard/state/Account/index.ts
  src/modules/Dashboard/state/index.ts
  src/shared/api/api.ts
  src/shared/api/api.types.ts
  src/shared/features/SwitchWorkspace/WorkspaceImage/WorkspaceImage.tsx
  src/shared/features/SwitchWorkspace/WorkspaceImage/WorkspaceImage.types.ts
  src/shared/hooks/alertsWebsocket/alertsWebsocket.const.ts
  src/shared/hooks/alertsWebsocket/alertsWebsocket.hooks.ts
  src/shared/hooks/alertsWebsocket/alertsWebsocket.types.ts
  src/shared/hooks/alertsWebsocket/alertsWebsocket.utils.ts
  src/shared/hooks/alertsWebsocket/index.ts
  src/shared/hooks/index.ts
  src/shared/hooks/useIntersectionObserver.ts
  src/shared/layouts/BaseLayout/BaseLayout.tsx
  src/shared/layouts/BaseLayout/components/TopBar/AccountPanel/AccountPanel.tsx
  src/shared/layouts/BaseLayout/components/TopBar/AccountPanel/AccountPanel.types.ts
  src/shared/layouts/BaseLayout/components/TopBar/Notifications/Notification/Notification.styles.ts
  src/shared/layouts/BaseLayout/components/TopBar/Notifications/Notification/Notification.tsx
  src/shared/layouts/BaseLayout/components/TopBar/Notifications/Notification/Notification.types.ts
  src/shared/layouts/BaseLayout/components/TopBar/Notifications/Notifications.const.ts
  src/shared/layouts/BaseLayout/components/TopBar/Notifications/Notifications.hooks.ts
  src/shared/layouts/BaseLayout/components/TopBar/Notifications/Notifications.styles.ts
  src/shared/layouts/BaseLayout/components/TopBar/Notifications/Notifications.tsx
  src/shared/layouts/BaseLayout/components/TopBar/Notifications/Notifications.types.ts
  src/shared/layouts/BaseLayout/components/TopBar/TopBar.tsx
  src/shared/state/Alerts/Alerts.const.ts
  src/shared/state/Alerts/Alerts.reducer.ts
  src/shared/state/Alerts/Alerts.schema.ts
  src/shared/state/Alerts/Alerts.state.ts
  src/shared/state/Alerts/Alerts.thunk.ts
  src/shared/state/Alerts/Alerts.utils.ts
  src/shared/state/Alerts/index.ts
  src/shared/state/index.ts
  src/shared/styles/styledComponents/Container.ts
  src/shared/styles/styledComponents/Typography.ts
  src/shared/utils/getInfinityScrollData.ts
  src/shared/utils/index.ts
Labels: enhancement

#736 feat: M2-2565 Add Drag&drop functionality to Scores and Sections cards within Scores&Reports
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoresAndReports.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionScoreHeader/SectionScoreHeader.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionScoreHeader/SectionScoreHeader.types.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/Title/Title.tsx
  src/modules/Builder/features/ActivitySettings/TitleComponent/TitleComponent.styles.ts
  src/modules/Builder/features/ActivitySettings/TitleComponent/TitleComponent.tsx
Labels: enhancement, Done

#741 fix: M2-2871 Data export: Flanker: There is 'R' response when the left('L') button was tapped
  src/shared/utils/exportData/getFlankerRecords.ts
Labels: bug, Done

#742 feat: M2-2910 Add description and activity count to the Share applet modal
  src/modules/Dashboard/features/Applet/Popups/SucessSharePopup/SuccessSharePopup.tsx
  src/modules/Dashboard/features/Applet/ShareApplet/ShareApplet.tsx
  src/modules/Dashboard/features/Applet/ShareApplet/SuccessShared/SuccessShared.tsx
  src/modules/Dashboard/features/Applet/ShareApplet/SuccessShared/SuccessShared.types.ts
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/components/FormComponents/TagsController/TagsController.styles.ts
  src/shared/state/Applet/Applet.schema.ts
Labels: Done

#743 feat: M2-2911 Add GET all applets to the according modal in the library
  src/modules/Dashboard/api/api.types.ts
  src/modules/Library/features/Popups/AddToBuilderPopup/AddToBuilderPopup.tsx
Labels: Done

#749 fix: M2-2618 Android. Application crashes on Item with video added to Displayed Content section. Changed video ouput to (![desc](videoUrl)).
  src/shared/components/MarkDownEditor/MarkDownEditor.const.ts
  src/shared/components/MarkDownEditor/MarkDownEditor.utils.ts
  src/shared/components/MarkDownEditor/extensions/VideoUploadExtension/VideoUploadExtension.tsx
  src/shared/consts.tsx
Labels: bug, Done

#750 fix: M2-2913 Audio Record: "click to browse" text is not displayed as a link in the "Upload Audio" dialog window
  src/modules/Builder/components/MediaUploader/MediaUploader.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/AudioPlayer/UploadAudio/UploadAudio.tsx
  src/resources/app-en.json
Labels: bug, Done

#753 fix: M2-2679 H1 and H2 are the same size in the markdown preview
  src/shared/components/MarkDownEditor/MarkDownEditor.styles.ts
Labels: bug, Done

#754 fix: M2-632 Applet About Page: It is possible to enter more than 55 characters in the Applet Name
  src/modules/Builder/features/AboutApplet/AboutApplet.tsx
Labels: bug, Done

#755 feat: M2-2931 Add Time Range as an outcome item in the Summary row of the Conditional card
  src/modules/Builder/features/ActivityItemsFlow/ItemFlow/ItemFlow.styles.ts
  src/modules/Builder/features/ActivityItemsFlow/ItemFlow/ItemFlow.tsx
  src/modules/Builder/features/ActivityItemsFlow/ItemFlow/SummaryRow/SummaryRow.const.ts
Labels: enhancement, Done

#763 fix: M2-2954 Wrong instructional text in CST Touch activity overview instruction
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
  src/resources/app-en.json
Labels: bug, Done

#769 fix: M2-2758 The unexpected value is present in the reports if no responses were provided yet
  src/modules/Builder/features/ActivitySettings/SubscalesConfiguration/LookupTable/LookupTable.hooks.ts
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/BlockSequences/BlockSequencesContent/BlockSequencesContent.tsx
  src/modules/Dashboard/features/Applet/Schedule/Legend/Legend.tsx
  src/shared/consts.tsx
  src/shared/utils/exportData/exportDataSucceed.ts
  src/shared/utils/exportTemplate.ts
Labels: bug, Done

#773 fix: M2-1731 Add user: wrong placeholder is displaying if select All Respondents
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.tsx
  src/resources/app-en.json
Labels: bug, Done

#774 fix: M2-1434 Scroll area in modals goes beyond corner
  src/modules/Dashboard/features/Applet/Schedule/Legend/SearchPopup/SearchPopup.styles.ts
  src/modules/Dashboard/features/Applet/Schedule/Legend/SearchPopup/SearchPopup.tsx
  src/shared/components/Modal/Modal.styles.ts
  src/shared/components/Modal/Modal.tsx
  src/shared/styles/styledComponents/Modal.ts
Labels: bug, Done

#779 fix: M2-2974 Alerts. It's possible to add more than one combination Slider + Option and Alert for them for Slider Rows
  src/modules/Builder/features/ActivityItems/ItemConfiguration/Alerts/Alert/Alert.utils.ts
  src/shared/components/FormComponents/SelectController/SelectController.styles.ts
  src/shared/components/FormComponents/SelectController/SelectController.tsx
  src/shared/components/FormComponents/SelectController/SelectController.types.ts
Labels: bug, Done

#788 fix: M2-682 Search field background color is EFF4FA instead of 72777F 8%
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ReportTable/ReportTable.tsx
  src/shared/components/Search/Search.styles.ts
Labels: bug, Done

#786 fix: M2-2977 Notes can't be saved
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Feedback/FeedbackNotes/FeedbackNote/FeedbackNote.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Feedback/FeedbackNotes/FeedbackNotes.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/RespondentDataReview.tsx
Labels: bug, Done

#785 fix: share to the library received url fix
  src/modules/Dashboard/features/Applet/ShareApplet/ShareApplet.tsx
Labels: bug, Done

#791 fix: M2-2985 After the successful Sign Up via the Library, the User is being navigated to the Admin Panel instead of the page, from which the Login process has been initiated
  src/modules/Auth/features/Login/LoginForm/LoginForm.tsx
  src/modules/Auth/features/SignUp/SignUpForm/SignUpForm.tsx
  src/shared/utils/index.ts
  src/shared/utils/navigateToLibrary.ts
Labels: bug, Done

#798 fix: M2-2989 Select Respondents checkboxes are working incorrectly
  src/modules/Dashboard/features/Managers/Popups/ManagersEditAccessPopup/Applet/Applet.styles.ts
  src/modules/Dashboard/features/Managers/Popups/SelectRespondentsPopup/SelectRespondents/SelectRespondents.const.tsx
  src/modules/Dashboard/features/Managers/Popups/SelectRespondentsPopup/SelectRespondents/SelectRespondents.tsx
  src/modules/Dashboard/features/Managers/Popups/SelectRespondentsPopup/SelectRespondents/SelectRespondents.utils.tsx
  src/shared/components/FormComponents/CheckboxController/CheckboxController.tsx
  src/shared/components/FormComponents/CheckboxController/CheckboxController.types.ts
Labels: bug, Done

#803 fix: M2-3009 The extra pop-up about unsaved changes appears if activity is copied from Library
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.hooks.ts
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.tsx
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.types.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.tsx
Labels: bug, Done

#799 fix: M2-2990 Library/View details: Checkboxes for the already added to the cart activities are unselected until clicking expand/collapse
  src/modules/Library/features/Applet/Activity/Activity.tsx
  src/modules/Library/features/Applet/Applet.styles.ts
  src/modules/Library/features/Applet/Applet.tsx
  src/modules/Library/features/Cart/Cart.tsx
  src/modules/Library/features/Popups/AddToBuilderPopup/AddToBuilderPopup.utils.tsx
Labels: bug, Done

#807 fix: M2-2955 Activity Flow is not copied from the Library after adding to builder all the activities included to the Activity Flow, M2-3016 Item Flow is not copied from the Library after adding to builder all the items included to the Item Flow
  src/modules/Library/features/Popups/AddToBuilderPopup/AddToBuilderPopup.utils.tsx
Labels: bug, Done

#814 fix: M2-3034 There is an empty applet after saving the applet from the Library until go to dashboard -> Edit applet
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.hooks.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.tsx
  src/modules/Dashboard/features/Applet/Popups/DeletePopup/DeletePopup.tsx
Labels: bug, Done

#819 fix: M2-1535 POST /applet: "isHidden = true" is not saved for activity item
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
  src/modules/Builder/types/Builder.types.ts
  src/shared/state/Applet/Applet.schema.ts
Labels: bug, Done

#818 fix: M2-3039 Coordinator/Reviewer is able to 'Add to Builder' to the shared workspace
  src/modules/Builder/features/Activities/ActivitiesHeader/ActivitiesHeader.tsx
  src/modules/Library/features/Cart/Cart.tsx
  src/modules/Library/features/Popups/AddToBuilderPopup/AddToBuilderPopup.tsx
  src/modules/Library/features/Popups/AddToBuilderPopup/AddToBuilderPopup.types.ts
  src/modules/Library/features/Popups/AddToBuilderPopup/AddToBuilderPopup.utils.tsx
  src/shared/components/FormComponents/RadioGroupController/RadioGroupController.styles.ts
  src/shared/components/FormComponents/RadioGroupController/RadioGroupController.tsx
  src/shared/components/Spinner/Spinner.styles.ts
  src/shared/components/Spinner/Spinner.tsx
  src/shared/components/Spinner/Spinner.types.ts
  src/shared/state/Workspaces/Workspaces.reducer.ts
  src/shared/state/Workspaces/Workspaces.schema.ts
  src/shared/state/Workspaces/Workspaces.state.ts
  src/shared/state/Workspaces/Workspaces.thunk.ts
  src/shared/state/Workspaces/index.ts
  src/shared/styles/styledComponents/Modal.ts
  src/shared/styles/variables/palette.ts
Labels: bug, Done

#822 fix: M2-2970 Alerts. 'data_matrix must have the same length as options' error on Single Selection per Row save
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SelectionRows/Header/Header.tsx
Labels: bug, Done

#825 fix: M2-2057 Data Retention. Data Retention period is not saving. Removed builder session storage.
  src/modules/Builder/components/SaveChangesPopup/SaveChangesPopup.tsx
  src/modules/Builder/features/ActivityAbout/ActivityAbout.tsx
  src/modules/Builder/features/ActivityFlowAbout/ActivityFlowAbout.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreCondition/ScoreCondition.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoresAndReports.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionContent/SectionContent.tsx
  src/modules/Builder/features/ActivitySettings/SubscalesConfiguration/SubscaleContent/SubscaleContent.tsx
  src/modules/Builder/features/ActivitySettings/SubscalesConfiguration/SubscalesConfiguration.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/GeneralSettings/ButtonsScreen/ButtonsContent/ButtonsContent.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/GeneralSettings/FixationScreen/FixationContent/FixationContent.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/RoundOptions/RoundOptions.tsx
  src/modules/Builder/features/PerformanceTasks/GyroscopeAndTouch/GeneralSettings/GeneralSettings.tsx
  src/modules/Builder/features/PerformanceTasks/NameDescription/NameDescriptionContent/NameDescriptionContent.tsx
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.hooks.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.tsx
  src/shared/components/CropPopup/CropPopup.types.ts
  src/shared/components/Uploader/Uploader.tsx
  src/shared/consts.tsx
  src/shared/features/AppletSettings/AppletSettings.hooks.ts
  src/shared/features/AppletSettings/DataRetentionSetting/DataRetention.tsx
  src/shared/hooks/index.ts
  src/shared/hooks/useBuilderSessionStorage.ts
  src/shared/hooks/useRemoveAppletData.ts
  src/shared/utils/index.ts
  src/shared/utils/sessionStorage.ts
Labels: bug, Done

#826 feat: M2-3086 Add auth/logout API call on logout
  src/modules/Auth/api/api.ts
  src/shared/api/api.client.ts
  src/shared/api/api.const.ts
  src/shared/hooks/useLogout.ts
  src/shared/hooks/usePermissions.tsx
Labels: Done

#829 fix: M2-3042 Alerts. Not all alerts are displaying in the list. M2-3043 Alerts from previous user are displaying for new user.
  src/shared/hooks/useIntersectionObserver.ts
  src/shared/hooks/useLogout.ts
  src/shared/state/Alerts/Alerts.reducer.ts
  src/shared/state/Alerts/index.ts
  src/shared/styles/styledComponents/Container.ts
Labels: bug, Done

#834 fix: M2-3085 Schedule tab. Switching between Individual Schedule and Default Schedule is not refreshing calendar.
  src/modules/Dashboard/features/Applet/Schedule/Calendar/Calendar.tsx
  src/modules/Dashboard/features/Applet/Schedule/Schedule.hooks.ts
  src/modules/Dashboard/features/Applet/Schedule/Schedule.tsx
Labels: bug, Done

#835 fix: M2-3105 Editor is not able to 'Add to Builder' to the shared workspace.
  src/modules/Library/features/Popups/AddToBuilderPopup/AddToBuilderPopup.tsx
  src/modules/Library/features/Popups/AddToBuilderPopup/AddToBuilderPopup.utils.tsx
  src/shared/components/FormComponents/SelectController/SelectController.tsx
  src/shared/utils/isManagerOrOwner.ts
Labels: bug, Done

#842 fix: M2-3140 Report Configuration. Report Server configuration resets after Save and Publish click.
  src/shared/api/api.utils.ts
Labels: bug, Done

#843 fix: M2-3017 After clicking 'Add to Builder' with single Workspace + no existing Applets the new Builder page is not opened.
  src/modules/Library/features/Cart/Cart.hooks.ts
  src/modules/Library/features/Cart/Cart.tsx
  src/modules/Library/features/Cart/Cart.utils.ts
  src/modules/Library/features/Popups/AddToBuilderPopup/AddToBuilderPopup.tsx
  src/modules/Library/features/Popups/AddToBuilderPopup/AddToBuilderPopup.types.ts
  src/modules/Library/features/Popups/AddToBuilderPopup/AddToBuilderPopup.utils.tsx
Labels: bug, Done

#844 fix: M2-3044 Share to Library: Number of Activities within the Applet is missing if share from applet builder.
  src/modules/Builder/features/BuilderAppletSettings/BuilderAppletSettings.utils.tsx
  src/modules/Dashboard/features/Applet/Popups/SucessSharePopup/SuccessSharePopup.tsx
  src/modules/Dashboard/features/Applet/ShareApplet/ShareApplet.tsx
  src/shared/features/AppletSettings/ShareAppletSetting/ShareAppletSetting.styles.ts
Labels: bug, Done

#850 fix: M2-3168 Schedule: A monthly event appears in the calendar one month longer than the scheduled one.
  src/modules/Dashboard/features/Applet/Schedule/Legend/Legend.hooks.tsx
  src/modules/Dashboard/state/CalendarEvents/CalendarEvents.reducer.ts
  src/modules/Dashboard/state/CalendarEvents/CalendarEvents.schema.ts
  src/modules/Dashboard/state/CalendarEvents/CalendarEvents.state.ts
  src/modules/Dashboard/state/CalendarEvents/CalendarEvents.utils.ts
  src/modules/Dashboard/state/CalendarEvents/index.ts
Labels: bug, Done

#851 Fix/m2 3061 wrong checkbox behaviour for allow respondent to skip all items
  src/modules/Builder/features/ActivityAbout/ActivityAbout.hooks.ts
  src/modules/Builder/features/ActivityAbout/ActivityAbout.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ItemConfiguration.utils.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/OptionalItemsAndSettings/OptionalItemsAndSettings.hooks.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/Settings/ItemSettingsController/ItemSettingsGroup/ItemSettingsGroup.tsx
  src/resources/app-en.json
  src/resources/app-fr.json
Labels: bug

#855 fix: M2-3029 It is not possible to update the single select item with score to multiple select and add response options.
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ConfigurationHeader/ConfigurationHeader.styles.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ConfigurationHeader/ConfigurationHeader.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ConfigurationHeader/ConfigurationHeader.types.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ConfigurationHeader/index.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ItemConfiguration.styles.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ItemConfiguration.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/OptionalItemsAndSettings/OptionalItemsAndSettings.hooks.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/OptionalItemsAndSettings/OptionalItemsAndSettings.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/OptionalItemsAndSettings/OptionalItemsAndSettings.types.ts
Labels: bug, Done

#858 fix: M2-3080 Share to Library: Applet name is not updated in the success pop-up after entering the new unique name and clicking the 'Share to Library' btn.
  src/modules/Dashboard/features/Applet/ShareApplet/ShareApplet.tsx
  src/modules/Dashboard/features/Applet/ShareApplet/ShareApplet.types.ts
  src/modules/Dashboard/features/Applet/ShareApplet/index.ts
  src/shared/features/AppletSettings/ShareAppletSetting/ShareAppletSetting.tsx
Labels: bug, Done

#852 Fix/m2 3033 it is possible to delete item referenced by variable
  src/modules/Builder/features/ActivityItems/ActivityItems.tsx
  src/modules/Builder/features/ActivityItems/ActivityItems.types.ts
  src/modules/Builder/features/ActivityItems/ActivityItems.utils.ts
  src/modules/Builder/features/ActivityItems/DeleteItemModal/DeleteItemModal.tsx
  src/modules/Builder/features/ActivityItems/DeleteItemModal/DeleteItemModal.types.ts
  src/modules/Builder/features/ActivityItems/DeleteItemModal/index.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/OptionalItemsAndSettings/SkippedItemInVariablesModal/SkippedItemInVariablesModal.hooks.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/OptionalItemsAndSettings/SkippedItemInVariablesModal/SkippedItemInVariablesModal.types.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/OptionalItemsAndSettings/SkippedItemInVariablesModal/SkippedItemInVariablesModal.utils.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.const.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.schema.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
  src/resources/app-en.json
  src/resources/app-fr.json
Labels: bug

#861 Fix/m2 3157 wrong validation in subscale lookup table
  src/modules/Builder/features/ActivitySettings/SubscalesConfiguration/LookupTable/LookupTable.hooks.ts
  src/shared/components/FileUploader/FileUploader.tsx
  src/shared/components/FileUploader/FileUploader.types.ts
Labels: bug

#862 fix: M2-3124 Report Configuration. Item Value checkbox is not saving after Save and Publish.
  src/modules/Builder/features/BuilderAppletSettings/BuilderAppletSettings.tsx
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.utils.ts
Labels: bug, Done
