Repository ChildMindInstitute/mindlogger-admin, pull requests merged in 2024-01, with the labels that each got.

#1340 M2-4522: M2-4523: M2-4545: Link Popup, Duplicate and PublishConceal a…
  src/modules/Dashboard/features/Applet/AddUser/Popups/LinkPopup/LinkPopup.test.tsx
  src/shared/features/AppletSettings/DuplicateAppletSettings/DuplicateAppletSettings.test.tsx
  src/shared/features/AppletSettings/PublishConcealAppletSetting/PublishConcealAppletSetting.test.tsx
Labels: tests

#1330 M2-4474: Test coverage for Schedule.utils.tsx, Schedule.hooks.ts
  src/modules/Dashboard/features/Applet/Schedule/Schedule.hooks.test.tsx
  src/modules/Dashboard/features/Applet/Schedule/Schedule.utils.test.ts
  src/modules/Dashboard/features/Applet/Schedule/Schedule.utils.tsx
  src/modules/Dashboard/state/Applets/Applets.schema.ts
  src/modules/Dashboard/state/CalendarEvents/CalendarEvents.schema.ts
  src/modules/Dashboard/state/CalendarEvents/CalendarEvents.utils.ts
Labels: tests

#1342 M2-4550: Unit tests for Unsupported Item Response component
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Feedback/FeedbackAssessment/SubmitAssessmentPopup/SubmitAssessmentPopup.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Review/Review.utils.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Review/Review.utils.test.tsx
  src/modules/Dashboard/features/RespondentData/UnsupportedItemResponse/UnsupportedItemResponse.test.tsx
Labels: tests

#1343 Tests/m2 4555 unit tests for items
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/MultiSelectResponseItem/MultiSelectResponseItem.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/RespondentDataReview.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/SingleSelectResponseItem/SingleSelectResponseItem.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/SliderResponseItem/SliderResponseItem.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/SliderResponseItem/SliderResponseItem.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/TextResponseItem/TextResponseItem.test.tsx
Labels: tests

#1339 M2-4528, M2-4527: Add Users: no scroll in the “Pending Invitations” table if there are more than 5 lines, add the tooltip with the invitation link and the "Copy" icon.
  src/modules/Dashboard/components/DashboardTable/DashboardTable.tsx
  src/modules/Dashboard/components/DashboardTable/DashboardTable.types.ts
  src/modules/Dashboard/features/Applet/AddUser/AddUser.tsx
  src/modules/Dashboard/features/Applet/AddUser/InvitationsTable/InvitationWithTooltip/InvitationWithTooltip.styles.ts
  src/modules/Dashboard/features/Applet/AddUser/InvitationsTable/InvitationWithTooltip/InvitationWithTooltip.tsx
  src/modules/Dashboard/features/Applet/AddUser/InvitationsTable/InvitationWithTooltip/InvitationWithTooltip.types.ts
  src/modules/Dashboard/features/Applet/AddUser/InvitationsTable/InvitationWithTooltip/InvitationsWithTooltip.test.tsx
  src/modules/Dashboard/features/Applet/AddUser/InvitationsTable/InvitationWithTooltip/index.ts
  src/modules/Dashboard/features/Applet/AddUser/InvitationsTable/InvitationsTable.const.ts
  src/modules/Dashboard/features/Applet/AddUser/InvitationsTable/InvitationsTable.const.tsx
  src/modules/Dashboard/features/Applet/AddUser/InvitationsTable/InvitationsTable.test.tsx
  src/modules/Dashboard/features/Applet/AddUser/InvitationsTable/InvitationsTable.tsx
  src/modules/Dashboard/features/Applet/AddUser/InvitationsTable/InvitationsTable.types.ts
  src/modules/Dashboard/features/Applet/AddUser/InvitationsTable/InvitationsTable.utils.tsx
  src/modules/Dashboard/features/Applet/Popups/DuplicatePopups/DuplicatePopups.test.tsx
  src/resources/app-en.json
  src/shared/components/Table/Table.types.ts
  src/shared/components/Tooltip/Tooltip.styles.tsx
  src/shared/components/Tooltip/Tooltip.tsx
  src/shared/components/Tooltip/Tooltip.types.ts
Labels: bug, enhancement, tests

#1329 M2-4463: M2-4464: TransferOwnership and ShareApplet settings tests
  src/modules/Dashboard/features/Applet/Popups/SucessSharePopup/SuccessSharePopup.test.tsx
  src/modules/Dashboard/features/Applet/Popups/SucessSharePopup/SuccessSharePopup.tsx
  src/modules/Dashboard/features/Applet/Popups/SucessSharePopup/SuccessSharePopup.types.ts
  src/modules/Dashboard/features/Applet/TransferOwnership/TransferOwnership.test.tsx
  src/shared/features/AppletSettings/ShareAppletSetting/ShareAppletSetting.test.tsx
  src/shared/features/AppletSettings/TransferOwnershipSetting/TransferOwnershipSetting.test.tsx
Labels: tests

#1344 M2- 4519: Test coverage for Calendar.tsx and Calendar.utils.tsx
  src/modules/Dashboard/features/Applet/Schedule/Calendar/Calendar.const.ts
  src/modules/Dashboard/features/Applet/Schedule/Calendar/Calendar.test.tsx
  src/modules/Dashboard/features/Applet/Schedule/Calendar/Calendar.tsx
  src/modules/Dashboard/features/Applet/Schedule/Calendar/Calendar.types.ts
  src/modules/Dashboard/features/Applet/Schedule/Calendar/Calendar.utils.test.ts
  src/modules/Dashboard/features/Applet/Schedule/Calendar/Calendar.utils.tsx
Labels: tests

#1346 M2-4510: Unit tests for Export Data Setting fix
  src/shared/features/AppletSettings/ExportDataSetting/ExportDataSetting.test.tsx
Labels: bug, tests

#1319 M2-4390: added coverage for exportDataSucceed
  src/shared/utils/exportData/exportDataSucceed.test.ts
  src/shared/utils/exportData/prepareData.ts
Labels: tests

#1347 M2-4668: Calendar: incorrect exported file when calendar is empty
  src/modules/Dashboard/features/Applet/Schedule/Legend/Legend.const.tsx
  src/modules/Dashboard/features/Applet/Schedule/Legend/Legend.tsx
Labels: bug

#1348 M2-4575: Text item: Length of correct answer can exceed "Max Characters" length
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/TextResponse/TextResponse.const.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/TextResponse/TextResponse.styles.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/TextResponse/TextResponse.tsx
Labels: bug

#1355 M2-4600: Add Users Tab changes
  src/modules/Dashboard/api/api.ts
  src/modules/Dashboard/api/api.types.ts
  src/modules/Dashboard/features/Applet/AddUser/AddUser.test.tsx
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.const.ts
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.hooks.ts
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.schema.ts
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.styles.tsx
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.test.tsx
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.tsx
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.types.ts
  src/modules/Dashboard/features/Applet/AddUser/InvitationsTable/InvitationsTable.test.tsx
  src/modules/Dashboard/features/Respondents/Popups/EditRespondentPopup/EditRespondentPopup.test.tsx
  src/modules/Dashboard/features/Respondents/Respondents.test.tsx
  src/resources/app-en.json
  src/resources/app-fr.json
Labels: enhancement, done

#1374 M2-4599: 'Add/Confirm email' popup on "invite them now" or "send invitation" click
  src/modules/Dashboard/api/api.ts
  src/modules/Dashboard/api/api.types.ts
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.const.ts
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.hooks.ts
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.tsx
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.types.ts
  src/modules/Dashboard/features/Applet/TransferOwnership/TransferOwnership.test.tsx
  src/modules/Dashboard/features/Respondents/Popups/SendInvitationPopup/SendInvitation.schema.ts
  src/modules/Dashboard/features/Respondents/Popups/SendInvitationPopup/SendInvitationPopup.const.ts
  src/modules/Dashboard/features/Respondents/Popups/SendInvitationPopup/SendInvitationPopup.test.tsx
  src/modules/Dashboard/features/Respondents/Popups/SendInvitationPopup/SendInvitationPopup.tsx
  src/modules/Dashboard/features/Respondents/Popups/SendInvitationPopup/SendInvitationPopup.types.ts
  src/modules/Dashboard/features/Respondents/Popups/SendInvitationPopup/index.ts
  src/modules/Dashboard/features/Respondents/Popups/index.ts
  src/modules/Dashboard/features/Respondents/Respondents.tsx
  src/modules/Dashboard/hooks/index.ts
  src/modules/Dashboard/hooks/useFormError.ts
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/components/Modal/Modal.tsx
  src/shared/components/Modal/Modal.types.ts
  src/shared/consts.tsx
Labels: enhancement, done

#1385 M2-4596: Shell Account - new "Actions" Menu
  src/modules/Dashboard/components/DashboardTable/DashboardTable.test.tsx
  src/modules/Dashboard/components/DashboardTable/DashboardTable.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/AppletItem/AppletItem.test.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/AppletItem/AppletItem.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/AppletItem/AppletItem.types.ts
  src/modules/Dashboard/features/Applets/AppletsTable/AppletItem/AppletItem.utils.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/AppletsTable.hooks.ts
  src/modules/Dashboard/features/Applets/AppletsTable/FolderItem/FolderItem.test.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/FolderItem/FolderItem.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/FolderItem/FolderItem.utils.tsx
  src/modules/Dashboard/features/Managers/Managers.test.tsx
  src/modules/Dashboard/features/Managers/Managers.tsx
  src/modules/Dashboard/features/Managers/Managers.types.ts
  src/modules/Dashboard/features/Managers/Managers.utils.tsx
  src/modules/Dashboard/features/Managers/Popups/ManagersEditAccessPopup/Applet/Applet.const.ts
  src/modules/Dashboard/features/Respondents/Respondents.const.tsx
  src/modules/Dashboard/features/Respondents/Respondents.test.tsx
  src/modules/Dashboard/features/Respondents/Respondents.tsx
  src/modules/Dashboard/features/Respondents/Respondents.types.ts
  src/modules/Dashboard/features/Respondents/Respondents.utils.test.tsx
  src/modules/Dashboard/features/Respondents/Respondents.utils.tsx
  src/shared/components/ActionsMenu/ActionsMenu.styles.ts
  src/shared/components/ActionsMenu/ActionsMenu.test.tsx
  src/shared/components/ActionsMenu/ActionsMenu.tsx
  src/shared/components/ActionsMenu/ActionsMenu.types.ts
  src/shared/components/ActionsMenu/index.ts
  src/shared/components/ButtonWithMenu/ButtonWithMenu.types.ts
  src/shared/components/Menu/Menu.const.ts
  src/shared/components/Menu/Menu.styles.tsx
  src/shared/components/Menu/Menu.test.tsx
  src/shared/components/Menu/Menu.tsx
  src/shared/components/Menu/Menu.types.ts
  src/shared/components/Menu/index.ts
  src/shared/components/Table/Table.types.ts
  src/shared/components/index.ts
Labels: enhancement, done

#1388 M2-4800: Add adjustments to allow unit tests to launch in the pipeline
  .gitignore
  package-lock.json
  package.json
  src/modules/Builder/features/PerformanceTasks/Flanker/Flanker.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/RespondentDataReview.test.tsx
Labels: enhancement, done

#1412 M2-4592, M2-4593, M2-4595: Applet and Dashboard Respondents Tab changes, Popups for Actions
  src/modules/Dashboard/api/api.ts
  src/modules/Dashboard/api/api.types.ts
  src/modules/Dashboard/features/Applets/Applets.const.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/AppletItem/AppletItem.utils.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/FolderItem/FolderItem.utils.tsx
  src/modules/Dashboard/features/Managers/Managers.utils.tsx
  src/modules/Dashboard/features/Respondents/Popups/EditRespondentPopup/EditRespondentPopup.tsx
  src/modules/Dashboard/features/Respondents/Popups/RespondentsRemoveAccessPopup/RespondentAccessPopup.utils.tsx
  src/modules/Dashboard/features/Respondents/Popups/RespondentsRemoveAccessPopup/RespondentsRemoveAccessPopup.test.tsx
  src/modules/Dashboard/features/Respondents/Popups/RespondentsRemoveAccessPopup/RespondentsRemoveAccessPopup.tsx
  src/modules/Dashboard/features/Respondents/Popups/RespondentsRemoveAccessPopup/RespondentsRemoveAccessPopup.types.ts
  src/modules/Dashboard/features/Respondents/Popups/SendInvitationPopup/SendInvitationPopup.const.ts
  src/modules/Dashboard/features/Respondents/Popups/SendInvitationPopup/SendInvitationPopup.test.tsx
  src/modules/Dashboard/features/Respondents/Popups/SendInvitationPopup/SendInvitationPopup.tsx
  src/modules/Dashboard/features/Respondents/Popups/SendInvitationPopup/SendInvitationPopup.types.ts
  src/modules/Dashboard/features/Respondents/Respondents.const.tsx
  src/modules/Dashboard/features/Respondents/Respondents.test.tsx
  src/modules/Dashboard/features/Respondents/Respondents.tsx
  src/modules/Dashboard/features/Respondents/Respondents.types.ts
  src/modules/Dashboard/features/Respondents/Respondents.utils.test.tsx
  src/modules/Dashboard/features/Respondents/Respondents.utils.tsx
  src/modules/Dashboard/features/Respondents/StatusFlag/StatusFlag.styles.ts
  src/modules/Dashboard/features/Respondents/StatusFlag/StatusFlag.test.tsx
  src/modules/Dashboard/features/Respondents/StatusFlag/StatusFlag.tsx
  src/modules/Dashboard/features/Respondents/StatusFlag/StatusFlag.types.ts
  src/modules/Dashboard/types/Dashboard.types.ts
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/components/Menu/Menu.styles.tsx
  src/shared/components/Menu/Menu.tsx
  src/shared/components/Menu/Menu.types.ts
  src/shared/mock.ts
  src/shared/styles/variables/palette.ts
Labels: enhancement, done

#1417 M2-4767: Send an invitation with a different ID to the shell account with the "Not invited" flag
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.const.ts
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.styles.tsx
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.tsx
  src/modules/Dashboard/hooks/useFormError.ts
  src/resources/app-en.json
  src/resources/app-fr.json
Labels: enhancement

#1431 M2-4716, M2-4717: Activity Settings Scores - Items used to calculate scores fixes
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionContent/SectionContent.tsx
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/components/DataTable/DataTable.tsx
  src/shared/components/DataTable/DataTable.types.ts
  src/shared/components/FormComponents/TransferListController/TransferListController.tsx
Labels: bug

#1436 M2-4730: Drawing item: frame default to the whole image
  src/shared/components/CropPopup/CropPopup.tsx
  src/shared/components/Uploader/Uploader.tsx
Labels: bug

#1435 M2-4859: Wrong item validation after deleting and re-adding an activity
  src/modules/Builder/features/Activities/Activities.tsx
Labels: bug

#1438 M2-4521: fixed additional text in response of export data
  src/shared/utils/exportData/parseResponseValue.ts
Labels: bug

#1439 M2-4437, M2-4736: "Save Changes?" popup appears after saving the Performance task or Single/Multiple Select Item and then try going to the dashboard without changes
  src/modules/Builder/features/ActivityItems/ItemConfiguration/OptionalItemsAndSettings/OptionalItemsAndSettings.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__tests__/ItemConfigurationDisplayedContent.test.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/GeneralSettings/StimulusScreen/StimulusContent/StimulusContent.tsx
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.utils.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.tsx
Labels: bug, done

#1446 M2-4986: Error on Score and Reports save
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.test.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.utils.test.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.utils.ts
Labels: release bug

#1444 M2-4982: Calendar. Import of AA event is displaying error
  src/modules/Dashboard/features/Applet/Schedule/ImportSchedulePopup/ImportSchedulePopup.utils.tsx
  src/modules/Dashboard/state/CalendarEvents/CalendarEvents.utils.ts
  src/shared/consts.tsx
Labels: bug

#1450 M2-4601: Shell Account - Data Export changes (due to added subjectID)
  src/modules/Dashboard/api/api.types.ts
  src/modules/Dashboard/features/Respondents/Popups/DataExportPopup/DataExportPopup.tsx
  src/modules/Dashboard/features/Respondents/Popups/DataExportPopup/DataExportPopup.types.ts
Labels: enhancement

#1452 M2-5014: [Admin Panel] Scores&Reports: Score Condition name is missed in the Conditional Logic filter of the newly added Section (not Saved&Published) if change the name of Score Condition
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.utils.ts
Labels: bug
