Repository ChildMindInstitute/mindlogger-admin, pull requests merged in 2024-04, with the labels that each got.

#1612 M2-6074: [Admin panel] After creating new activity with conditional logic error occurs 'TypeError: Cannot read properties of undefined (reading 'reduce')'
  src/modules/Builder/features/ActivityItemsFlow/ItemFlow/SummaryRow/SummaryRow.types.ts
  src/modules/Builder/features/ActivityItemsFlow/ItemFlow/SummaryRow/SummaryRow.utils.test.ts
  src/modules/Builder/features/ActivityItemsFlow/ItemFlow/SummaryRow/SummaryRow.utils.ts
Labels: release bug

#1615 M2-6089: [Data Export] The 'undefined' or [Object Object] value is recorded in the 'activity-user-journey' if additional text response was selected before the item response option selection
  src/shared/utils/exportData/parseResponseValue.test.ts
  src/shared/utils/exportData/parseResponseValue.ts
Labels: bug

#1621 Update develop with the release changes
  src/modules/Builder/features/ActivityItemsFlow/ItemFlow/SummaryRow/SummaryRow.types.ts
  src/modules/Builder/features/ActivityItemsFlow/ItemFlow/SummaryRow/SummaryRow.utils.test.ts
  src/modules/Builder/features/ActivityItemsFlow/ItemFlow/SummaryRow/SummaryRow.utils.ts
  src/shared/utils/env.ts
  src/shared/utils/mixpanel.ts
Labels: sync (release to develop)

#1620 M2-5495: [Admin Panel] Unit tests for Subscales utils in Summary
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Subscales/Subscales.utils.test.ts
Labels: tests

#1610 M2-6035: [Admin panel] A/B Trails - Save Incomplete Round of the Test and Continue
  src/shared/consts.tsx
  src/shared/types/answer.ts
  src/shared/utils/exportData/getFlag.test.ts
  src/shared/utils/exportData/getFlag.ts
  src/shared/utils/exportData/getJourneyCSVObject.test.ts
  src/shared/utils/exportData/getJourneyCSVObject.ts
  src/shared/utils/exportData/getReportAndMediaData.test.ts
  src/shared/utils/exportData/getReportAndMediaData.ts
Labels: enhancement

#1611 M2-6056: [Admin Panel - Phase 1] - Allow to divide the space 50/50 between Drawing Example and Drawing Area
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/Drawing/DrawingContent/DrawingContent.test.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/Drawing/DrawingContent/DrawingContent.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__mocks__/mock.tsx
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/components/FormComponents/CheckboxController/CheckboxController.tsx
  src/shared/components/FormComponents/CheckboxController/CheckboxController.types.ts
  src/shared/mock.ts
  src/shared/state/Applet/Applet.schema.ts
Labels: enhancement

#1625 M2-6137: [Admin Panel - Phase 1] - Disable feature until final solution
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/Drawing/DrawingContent/DrawingContent.test.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/Drawing/DrawingContent/DrawingContent.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__mocks__/mock.tsx
Labels: enhancement

#1635 M2-4661: [Admin Panel] Summary Tab: Wrong text displays when Versions filter is empty
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.tsx
  src/resources/app-en.json
  src/resources/app-fr.json
Labels: bug

#1636 M2-4702: [Admin Panel] DataViz: Activity header is missed on the Summary tab if open the Activity details
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/RespondentDataSummary.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/RespondentDataSummary.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/RespondentDataSummary.utils.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/RespondentDataSummary.utils.tsx
  src/shared/styles/styledComponents/StickyHeader.ts
Labels: bug

#1637 M2-6146: [Admin Panel] - Remove 'Mobile only' chip for Single Selection per Row and Multiple Selection per Row Item Types
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ItemConfiguration.const.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__mocks__/mock.tsx
Labels: bug

#1632 M2-6107: [Admin Panel] Unit tests for Subscales configuration in Builder
  src/modules/Builder/features/ActivitySettings/SubscalesConfiguration/SubscalesConfiguration.utils.test.tsx
  src/modules/Builder/features/ActivitySettings/SubscalesConfiguration/SubscalesConfiguration.utils.tsx
  src/modules/Builder/utils/removeMarkdown.test.ts
  src/shared/mock.ts
Labels: tests

#1649 Update develop with the release change
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/Drawing/DrawingContent/DrawingContent.test.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/Drawing/DrawingContent/DrawingContent.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__mocks__/mock.tsx
Labels: sync (release to develop)

#1658 M2-5552: DataViz Summary Tab: Adjust the default time range to 1 week from the most resent response within the selected Activity
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/RespondentDataReview.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/RespondentDataReview.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Review/Review.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Review/Review.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Review/Review.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Review/Review.utils.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Review/Review.utils.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/ReportMenu/ReportMenu.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/ReportMenu/ReportMenu.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/ReportMenu/ReportMenu.utils.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/ReportMenu/ReportMenu.utils.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/RespondentDataSummary.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/RespondentDataSummary.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/hooks/useDatavizSummaryRequests/useDatavizSummaryRequests.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/hooks/useDatavizSummaryRequests/useDatavizSummaryRequests.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/utils/getOneWeekDateRange.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/utils/getOneWeekDateRange.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/utils/setDateRangeValues.ts
  src/resources/app-en.json
  src/resources/app-fr.json
Labels: enhancement

#1660 Sync: release to develop
  .github/workflows/update-jira-tickets.yaml
Labels: sync (release to develop)

#1665 M2-5554: DataViz: Adjust filter once the Response Identifier is selected
  src/modules/Dashboard/features/RespondentData/RespondentData.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ReportFilters/ReportFilters.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ReportFilters/ReportFilters.utils.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/RespondentDataSummary.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/hooks/useDatavizSummaryRequests/useDatavizSummaryRequests.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/hooks/useDecryptedIdentifiers.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/hooks/useDecryptedIdentifiers.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/hooks/useRespondentAnswers/useRespondentAnswers.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/hooks/useRespondentAnswers/useRespondentAnswers.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/hooks/useRespondentAnswers/useRespondentAnswers.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/hooks/useRespondentAnswers/useRespondentAnswers.utils.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/hooks/useRespondentAnswers/useRespondentAnswers.utils.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/utils/getOneWeekDateRange.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/utils/getOneWeekDateRange.ts
Labels: enhancement

#1669 M2-5522: [Admin Panel] User remains at the Applet page after clicking on "Go to Dashboard" button
  src/modules/Auth/features/Login/LoginForm/LoginForm.tsx
  src/modules/Auth/features/RecoverPassword/RecoverForm/RecoverForm.test.tsx
  src/modules/Auth/features/RecoverPassword/RecoverForm/RecoverForm.tsx
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.hooks.ts
  src/modules/Library/features/Cart/Cart.utils.test.ts
  src/modules/Library/features/Cart/Cart.utils.ts
  src/modules/Library/features/Popups/AuthPopup/AuthPopup.tsx
  src/shared/components/AppletNotFoundPopup/AppletNotFoundPopup.hooks.tsx
  src/shared/components/AppletNotFoundPopup/AppletNotFoundPopup.test.tsx
  src/shared/components/NoPermissionPopup/NoPermissionPopup.hooks.test.ts
  src/shared/components/NoPermissionPopup/NoPermissionPopup.hooks.ts
  src/shared/components/NoPermissionPopup/NoPermissionPopup.types.ts
  src/shared/features/AppletSettings/AppletSettings.hooks.ts
  src/shared/layouts/BaseLayout/components/LeftBar/LeftBar.tsx
  src/shared/types/index.ts
  src/shared/types/navigation.ts
  src/shared/utils/authStorage.ts
Labels: bug

#1682 M2-6365: [Admin Panel] View Data: Summary page taking long time to respond/crashing
  src/modules/Builder/consts.ts
  src/modules/Builder/features/ActivityItems/LeftBar/DraggableItems/DraggableItems.tsx
  src/modules/Builder/features/ActivityItems/LeftBar/LeftBar.tsx
  src/modules/Builder/features/ActivityItemsFlow/ItemFlow/ItemFlow.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreCondition/ScoreCondition.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionContent/SectionContent.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/MultiScatterChart/MultiScatterChart.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/MultiScatterChart/MultiScatterChart.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/MultipleSelectionChart/MultipleSelectionChart.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/MultipleSelectionChart/MultipleSelectionChart.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/MultipleSelectionChart/index.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/ResponseOptions.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/ResponseOptions.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/ResponseOptions.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/ResponseOptions.utils.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/ResponseOptions.utils.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/RespondentDataSummary.const.ts
  src/shared/components/DatePicker/DatePicker.tsx
  src/shared/components/DatePicker/DatePicker.types.ts
  src/shared/components/MarkDownEditor/MarkDownEditor.utils.ts
  src/shared/consts.tsx
  src/shared/hooks/useStaticContent.ts
Labels: bug

#1689 M2-4378: [Admin Panel] Part of entered text is randomly removed after some text was deleted or symbols were added
  src/shared/components/FormComponents/EditorController/Editor/Editor.hooks.ts
  src/shared/components/FormComponents/EditorController/Editor/Editor.tsx
  src/shared/components/FormComponents/EditorController/Editor/Editor.types.ts
Labels: bug
