Repository ChildMindInstitute/mindlogger-admin, pull requests merged in 2024-03, with the labels that each got.

#1527 M2-5457: Add status message when shell account is created
  src/modules/Dashboard/components/Banners/ShellAccountSuccessBanner/ShellAccountSuccessBanner.const.ts
  src/modules/Dashboard/components/Banners/ShellAccountSuccessBanner/ShellAccountSuccessBanner.styles.ts
  src/modules/Dashboard/components/Banners/ShellAccountSuccessBanner/ShellAccountSuccessBanner.test.tsx
  src/modules/Dashboard/components/Banners/ShellAccountSuccessBanner/ShellAccountSuccessBanner.tsx
  src/modules/Dashboard/components/Banners/ShellAccountSuccessBanner/index.ts
  src/modules/Dashboard/components/Banners/index.ts
  src/modules/Dashboard/components/index.ts
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.test.tsx
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.tsx
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/components/Banners/Banners.const.ts
  src/shared/state/Banners/Banners.schema.ts
Labels: enhancement, done

#1538 M2-5420: Add stream ip address and port fields for default settings in Live settings
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.const.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.schema.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
  src/modules/Builder/types/Builder.types.ts
  src/modules/Library/features/Popups/AddToBuilderPopup/AddToBuilderPopup.test.tsx
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/features/AppletSettings/LiveResponseStreamingSetting/LiveResponseStreamingSetting.const.ts
  src/shared/features/AppletSettings/LiveResponseStreamingSetting/LiveResponseStreamingSetting.styles.ts
  src/shared/features/AppletSettings/LiveResponseStreamingSetting/LiveResponseStreamingSetting.test.tsx
  src/shared/features/AppletSettings/LiveResponseStreamingSetting/LiveResponseStreamingSetting.tsx
  src/shared/features/AppletSettings/LiveResponseStreamingSetting/LiveResponseStreamingSetting.types.ts
  src/shared/features/AppletSettings/LiveResponseStreamingSetting/LiveResponseStreamingSetting.utils.test.ts
  src/shared/features/AppletSettings/LiveResponseStreamingSetting/LiveResponseStreamingSetting.utils.ts
  src/shared/state/Applet/Applet.schema.ts
Labels: enhancement

#1509 M2-4897: Blank screen/Inconsistent info text for transfer ownership negative scenarios
  src/App.tsx
  src/modules/Builder/features/ReportConfigSetting/ReportConfigSetting.tsx
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.hooks.ts
  src/modules/Dashboard/features/Applet/Popups/DeletePopup/DeletePopup.test.tsx
  src/modules/Dashboard/features/Applet/Popups/DeletePopup/DeletePopup.tsx
  src/modules/Dashboard/features/Applet/Popups/DuplicatePopups/DuplicatePopups.test.tsx
  src/modules/Dashboard/features/Applet/Popups/DuplicatePopups/DuplicatePopups.tsx
  src/modules/Dashboard/features/Respondents/Respondents.tsx
  src/modules/Dashboard/state/Popups/Popups.reducer.ts
  src/redux/store/reducers.ts
  src/redux/store/store.ts
  src/resources/app-en.json
  src/resources/app-fr.json
  src/routes/index.tsx
  src/shared/api/api.client.ts
  src/shared/components/NoPermissionPopup/NoPermissionPopup.hooks.test.ts
  src/shared/components/NoPermissionPopup/NoPermissionPopup.hooks.ts
  src/shared/components/NoPermissionPopup/NoPermissionPopup.test.tsx
  src/shared/components/NoPermissionPopup/NoPermissionPopup.tsx
  src/shared/components/NoPermissionPopup/NoPermissionPopup.types.ts
  src/shared/components/NoPermissionPopup/index.ts
  src/shared/components/index.ts
  src/shared/features/AppletSettings/DataRetentionSetting/DataRetention.tsx
  src/shared/features/AppletSettings/TransferOwnershipSetting/TransferOwnershipSetting.test.tsx
  src/shared/hooks/usePermissions.tsx
  src/shared/state/ForbiddenState/ForbiddenState.reducer.ts
  src/shared/state/ForbiddenState/ForbiddenState.schema.ts
  src/shared/state/ForbiddenState/ForbiddenState.state.tsx
  src/shared/state/ForbiddenState/index.ts
  src/shared/state/index.ts
  src/shared/types/apiError.ts
  src/shared/utils/urlGenerator.ts
Labels: bug, done

#1543 M2-5003: Slider and Slider Rows Items Improvements
  src/modules/Builder/consts.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/Alerts/Alert/Alert.utils.test.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/Alerts/Alert/Alert.utils.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SliderRows/SliderPanel/SliderPanel.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ItemConfiguration.const.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__mocks__/mock.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__tests__/ItemConfigurationSliderRows.test.tsx
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
  src/resources/app-en.json
  src/resources/app-fr.json
Labels: enhancement, done

#1540 M2-5327: [Admin Panel] Website becomes unresponsive after opening the 'Scores'Reports' tab of PMHSA11+ applet
  src/modules/Builder/consts.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreCondition/ScoreCondition.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreCondition/ScoreCondition.types.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreCondition/StaticScoreCondition/StaticScoreCondition.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreCondition/StaticScoreCondition/index.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreCondition/StaticScoreConditionals/StaticScoreConditionals.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreCondition/StaticScoreConditionals/StaticScoreConditionals.types.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreCondition/StaticScoreConditionals/index.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.types.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/StaticScoreContent/StaticScoreContent.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/StaticScoreContent/StaticScoreContent.types.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/StaticScoreContent/index.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoresAndReports.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionContent/SectionContent.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionContent/SectionContent.types.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionContent/StaticSectionContent/StaticSectionContent.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionContent/StaticSectionContent/index.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionScoreCommonFields/SectionScoreCommonFields.tsx
  src/modules/Builder/utils/getObserverSelector.ts
  src/shared/hooks/useStaticContent.ts
Labels: bug

#1546 M2-5341: User is able to go forward without adding any data in required Additional text field
  src/modules/Builder/features/ActivityItems/ItemConfiguration/Settings/ItemSettingsController/ItemSettingsController.test.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/Settings/ItemSettingsController/ItemSettingsGroup/ItemSettingsGroup.tsx
Labels: bug, done

#1550 M2-5326: [Admin Panel] Script(injection) can be added to the ‘Show Message’ filed and saved
  .github/pull_request_template.md
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.utils.test.ts
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.utils.ts
  src/shared/utils/forms.test.ts
  src/shared/utils/forms.ts
Labels: bug

#1552 M2-5496: [Admin Panel] Summary tab: Hidden item displays if it's included in Sub-scales culculation
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Subscales/Subscales.utils.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Subscales/Subscales.utils.ts
Labels: bug

#1553 M2-4683: Inconsistent validation message if condition is incorrect
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionContent/SectionContent.const.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionContent/SectionContent.test.tsx
  src/modules/Builder/features/ActivitySettings/TitleComponent/TitleComponent.styles.ts
  src/modules/Builder/features/ActivitySettings/TitleComponent/TitleComponent.tsx
  src/modules/Builder/features/ActivitySettings/TitleComponent/TitleComponent.utils.test.ts
  src/modules/Builder/features/ActivitySettings/TitleComponent/TitleComponent.utils.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.const.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.schema.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/features/AppletSettings/LiveResponseStreamingSetting/LiveResponseStreamingSetting.test.tsx
Labels: bug, done

#1554 M2-4663: [Admin Panel] Review Tab: Review Date is not disabled if Activities in the Applet have never been completed by selected Respondent
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/RespondentDataReview.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/ReviewMenu/ReviewMenu.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/ReviewMenu/ReviewMenu.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/ReviewMenu/ReviewMenu.types.ts
Labels: bug

#1555 M2-4664: Schedule: Activity's name duplicated on Week view for Cross-day event (Next day)
  src/modules/Dashboard/features/Applet/Schedule/Calendar/Calendar.const.ts
  src/modules/Dashboard/features/Applet/Schedule/Calendar/Calendar.styles.ts
  src/modules/Dashboard/features/Applet/Schedule/Calendar/Calendar.utils.tsx
Labels: bug, done

#1556 M2-4710: The ‘Upload FileBody: File is too big’ is sometimes missing after an attempt to upload audio .mp3 with 150Mb+ size
  src/shared/components/MarkDownEditor/extensions/Extensions.hooks.ts
Labels: bug, done

#1558 M2-4660: [Admin Panel] Summary Tab: the header ‘Activities' and 'Respondent: [Secret User ID] ([First Name] [Last Name])’ are NOT fixed to the top of the panel
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/ReportMenu/ReportMenu.styles.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/ReportMenu/ReportMenu.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/ReportMenu/StickyHeader/StickyHeader.styles.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/ReportMenu/StickyHeader/StickyHeader.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/ReportMenu/StickyHeader/StickyHeader.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/ReportMenu/StickyHeader/StickyHeader.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/ReportMenu/StickyHeader/index.ts
  src/shared/components/ContentWithTooltip/ContentWithTooltip.tsx
  src/shared/components/ContentWithTooltip/ContentWithTooltip.types.ts
  src/shared/hooks/useHeaderSticky.test.tsx
  src/shared/hooks/useHeaderSticky.tsx
  src/shared/types/generics.ts
  src/shared/utils/testUtils.ts
Labels: bug

#1562 M2-5521: Need Item_Id in the data export files
  src/shared/types/answer.ts
  src/shared/utils/exportData/getJourneyCSVObject.test.ts
  src/shared/utils/exportData/getJourneyCSVObject.ts
  src/shared/utils/exportData/getReportAndMediaData.test.ts
  src/shared/utils/exportData/getReportCSVObject.test.ts
  src/shared/utils/exportData/getReportCSVObject.ts
  src/shared/utils/exportData/prepareData.test.ts
Labels: enhancement

#1563 Sync: merge release[1.16.1] into develop
  .github/pull_request_template.md
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.utils.test.ts
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.utils.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Subscales/Subscales.utils.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Subscales/Subscales.utils.ts
  src/shared/utils/forms.test.ts
  src/shared/utils/forms.ts
Labels: sync (release to develop)

#1574 M2-5783: [Admin panel] Export: Drawing responce file name isn't added to response column if item has Text input option
  src/shared/utils/exportData/parseResponseValue.test.ts
  src/shared/utils/exportData/parseResponseValue.ts
Labels: bug

#1570 M2-5742: Dataviz - Number Selection Item support
  src/modules/Dashboard/features/RespondentData/RespondentData.consts.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/NumberSelectionResponseItem/NumberSelectionResponseItem.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/NumberSelectionResponseItem/NumberSelectionResponseItem.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/NumberSelectionResponseItem/index.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/RespondentDataReview.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Review/Review.utils.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Review/Review.utils.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/MultiScatterChart/MultiScatterChart.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/MultiScatterChart/MultiScatterChart.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/MultiScatterChart/MultiScatterChart.utils.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.utils.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.utils.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/ResponseOptions.utils.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/ResponseOptions.utils.tsx
Labels: enhancement

#1581 M2-5794: Dataviz - Date Item support
  src/modules/Dashboard/features/RespondentData/RespondentData.consts.ts
  src/modules/Dashboard/features/RespondentData/RespondentData.utils.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentData.utils.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/DateResponseItem/DateResponseItem.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/DateResponseItem/index.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/RespondentDataReview.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Review/Review.utils.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Review/Review.utils.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.utils.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.utils.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/ResponseOptions.utils.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/ResponseOptions.utils.tsx
  src/shared/components/DatePicker/DatePicker.styles.ts
  src/shared/components/DatePicker/DatePicker.tsx
  src/shared/components/DatePicker/DatePickerInput/DatePickerInput.test.tsx
  src/shared/components/DatePicker/DatePickerInput/DatePickerInput.tsx
  src/shared/components/DatePicker/DatePickerInput/DatePickerInput.types.ts
  src/shared/components/DatePicker/DatePickerInput/index.ts
Labels: enhancement

#1589 M2-5902: [Frontend] Add event_id to report
  src/shared/types/answer.ts
  src/shared/utils/exportData/getJourneyCSVObject.test.ts
  src/shared/utils/exportData/getJourneyCSVObject.ts
  src/shared/utils/exportData/getReportAndMediaData.test.ts
  src/shared/utils/exportData/getReportCSVObject.test.ts
  src/shared/utils/exportData/getReportCSVObject.ts
Labels: enhancement

#1590 M2-5903: [Frontend] Add timezone offset to data export
  src/shared/types/answer.ts
  src/shared/utils/exportData/getJourneyCSVObject.test.ts
  src/shared/utils/exportData/getJourneyCSVObject.ts
  src/shared/utils/exportData/getReportAndMediaData.test.ts
  src/shared/utils/exportData/getReportCSVObject.test.ts
  src/shared/utils/exportData/getReportCSVObject.ts
Labels: enhancement

#1591 M2-5895: [Admin] Update timestamp in Responses tab
  src/modules/Dashboard/api/api.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/ReviewMenu/ReviewMenuItem/ReviewMenuItem.tsx
Labels: enhancement

#1595 M2-5795: Dataviz - Time Range Item support
  src/modules/Dashboard/features/RespondentData/RespondentData.consts.ts
  src/modules/Dashboard/features/RespondentData/RespondentData.utils.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentData.utils.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/RespondentDataReview.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Review/Review.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Review/Review.utils.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Review/Review.utils.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/TimeRangeResponseItem/TimeRangeResponseItem.styles.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/TimeRangeResponseItem/TimeRangeResponseItem.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/TimeRangeResponseItem/index.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/LineChart/TimePickerLineChart/TimePickerLineChart.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/MultiScatterChart/MultiScatterChart.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.utils.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.utils.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ReportTable/ReportTable.const.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ReportTable/ReportTable.hooks.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ReportTable/ReportTable.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ReportTable/ReportTable.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ReportTable/ReportTable.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ReportTable/ReportTable.utils.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/ResponseOptions.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/ResponseOptions.utils.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/ResponseOptions.utils.tsx
  src/resources/app-en.json
  src/resources/app-fr.json
Labels: enhancement

#1598 M2-5915: [Admin Panel] - Item Flow Conditional Logic - Add validation if Item from the Summary row is already in use in another Conditional card
  src/modules/Builder/features/ActivityItemsFlow/ItemFlow/SummaryRow/SummaryRow.hooks.ts
  src/modules/Builder/features/ActivityItemsFlow/ItemFlow/SummaryRow/SummaryRow.tsx
  src/modules/Builder/features/ActivityItemsFlow/ItemFlow/SummaryRow/SummaryRow.types.ts
  src/modules/Builder/features/ActivityItemsFlow/ItemFlow/SummaryRow/SummaryRow.utils.test.ts
  src/modules/Builder/features/ActivityItemsFlow/ItemFlow/SummaryRow/SummaryRow.utils.ts
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/components/FormComponents/SelectController/SelectController.tsx
Labels: bug

#1600 M2-5905: Add data-testIds on "Applet Library" page
  src/modules/Library/features/Applet/Applet.tsx
Labels: enhancement
