Repository ChildMindInstitute/mindlogger-admin, pull requests merged in 2024-02, with the labels that each got.

#1449 M2-5028: added debugMode for qa purpose
  src/shared/utils/env.ts
  src/shared/utils/exportData/prepareData.ts
  src/shared/utils/logger.ts
  src/shared/utils/mixpanel.ts
  src/shared/utils/storage.ts
Labels: enhancement

#1457 M2-5042: Builder - Newly added Activity Item disappears after switching to another
  src/modules/Builder/features/ActivityItems/ItemConfiguration/OptionalItemsAndSettings/OptionalItemsAndSettings.hooks.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/OptionalItemsAndSettings/OptionalItemsAndSettings.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/OptionalItemsAndSettings/OptionalItemsAndSettings.types.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/Settings/ItemSettingsController/ItemSettingsGroup/ItemSettingsGroup.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__mocks__/mock.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__tests__/ItemConfigurationSelectionRows.test.tsx
Labels: bug

#1453 M2-5013: [Admin Panel] Scores&Reports: the "if" dropdown should be without the arrow in the Score Condition section because it is disabled
  src/modules/Builder/components/ConditionRow/Condition/Condition.tsx
  src/shared/components/FormComponents/SelectController/SelectController.tsx
  src/shared/components/FormComponents/SelectController/SelectController.types.ts
Labels: bug

#1454 M2-4892: Dataviz page: Blinking between Review and Summary tabs and the type errors in console
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__tests__/ItemConfigurationSelectionRows.test.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__tests__/ItemConfigurationSingleMultiSelect.test.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__tests__/ItemConfigurationSliderRows.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/RespondentDataReview.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/ReviewMenu/ReviewMenu.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ReportFilters/ReportFilters.test.tsx
  src/shared/components/DatePicker/DatePicker.styles.ts
  src/shared/components/DatePicker/DatePicker.tsx
  src/shared/components/TimePicker/TimePicker.tsx
  src/shared/consts.tsx
Labels: bug

#1458 M2-4712: M2-4731: Upload Image: success popup, crop collapse fix
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/components/CropPopup/CropPopup.const.ts
  src/shared/components/CropPopup/CropPopup.tsx
  src/shared/components/CropPopup/CropPopup.utils.ts
  src/shared/components/Uploader/RemoveImagePopup/RemoveImagePopup.tsx
  src/shared/components/Uploader/RemoveImagePopup/RemoveImagePopup.types.ts
  src/shared/components/Uploader/RemoveImagePopup/RemoveImagePopup.utils.ts
  src/shared/components/Uploader/Uploader.test.tsx
  src/shared/components/Uploader/Uploader.tsx
Labels: bug

#1463 M2-4759: [Admin Panel] Summary tab: "Respondent skipped the response" message is shown for hidden Text item
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.utils.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Report.utils.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ReportTable/ReportTable.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ReportTable/ReportTable.tsx
Labels: bug

#1465 M2-4592: M2-4593: Respondents tab: changes according to updated API contracts
  src/modules/Dashboard/api/api.ts
  src/modules/Dashboard/api/api.types.ts
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.tsx
  src/modules/Dashboard/features/Applet/Schedule/Legend/Legend.tsx
  src/modules/Dashboard/features/Applet/Schedule/Legend/SearchPopup/SearchPopup.tsx
  src/modules/Dashboard/features/Applet/Schedule/RemoveIndividualSchedulePopup/RemoveIndividualSchedulePopup.tsx
  src/modules/Dashboard/features/Applet/Schedule/Schedule.tsx
  src/modules/Dashboard/features/Managers/Popups/SelectRespondentsPopup/SelectRespondentsPopup.test.tsx
  src/modules/Dashboard/features/Managers/Popups/SelectRespondentsPopup/SelectRespondentsPopup.tsx
  src/modules/Dashboard/features/Respondents/Popups/DataExportPopup/DataExportPopup.tsx
  src/modules/Dashboard/features/Respondents/Popups/EditRespondentPopup/EditRespondentPopup.test.tsx
  src/modules/Dashboard/features/Respondents/Popups/EditRespondentPopup/EditRespondentPopup.tsx
  src/modules/Dashboard/features/Respondents/Popups/RespondentsRemoveAccessPopup/RespondentsRemoveAccessPopup.test.tsx
  src/modules/Dashboard/features/Respondents/Popups/RespondentsRemoveAccessPopup/RespondentsRemoveAccessPopup.tsx
  src/modules/Dashboard/features/Respondents/Popups/ScheduleSetupPopup/ScheduleSetupPopup.test.tsx
  src/modules/Dashboard/features/Respondents/Popups/ScheduleSetupPopup/ScheduleSetupPopup.tsx
  src/modules/Dashboard/features/Respondents/Popups/SendInvitationPopup/SendInvitationPopup.test.tsx
  src/modules/Dashboard/features/Respondents/Popups/SendInvitationPopup/SendInvitationPopup.tsx
  src/modules/Dashboard/features/Respondents/Popups/ViewDataPopup/ViewDataPopup.test.tsx
  src/modules/Dashboard/features/Respondents/Popups/ViewDataPopup/ViewDataPopup.tsx
  src/modules/Dashboard/features/Respondents/Respondents.tsx
  src/modules/Dashboard/features/Respondents/Respondents.types.ts
  src/modules/Dashboard/features/Respondents/Respondents.utils.test.tsx
  src/modules/Dashboard/features/Respondents/Respondents.utils.tsx
  src/modules/Dashboard/types/Dashboard.types.ts
  src/shared/mock.ts
Labels: enhancement

#1466 M2-4424: [Admin Panel Rewriting] Add test ids for non-editable activity items
  src/modules/Builder/features/ActivityItems/LeftBar/DraggableItems/DraggableItem/DraggableItem.tsx
  src/modules/Builder/features/ActivityItems/LeftBar/Item/Item.tsx
  src/modules/Builder/features/ActivityItems/LeftBar/Item/Item.types.ts
  src/modules/Builder/features/ActivityItems/LeftBar/LeftBar.tsx
Labels: enhancement

#1467 M2-1273: [Admin Panel] Create Applet Password pop-up: error message for the “Repeat Password” field does not match the requirements
  src/resources/app-en.json
Labels: bug

#1464 M2-4969: [Admin Panel] Set up Banners infra for system messages
  package-lock.json
  package.json
  src/modules/Auth/layouts/AuthLayout/AuthLayout.tsx
  src/modules/Builder/components/Banners/AppletWithoutChangesBanner/AppletWithoutChangesBanner.tsx
  src/modules/Builder/components/Banners/AppletWithoutChangesBanner/index.ts
  src/modules/Builder/components/Banners/index.ts
  src/modules/Builder/components/Popups/AppletWithoutChangesPopup/AppletWithoutChangesPopup.test.tsx
  src/modules/Builder/components/Popups/AppletWithoutChangesPopup/AppletWithoutChangesPopup.tsx
  src/modules/Builder/components/Popups/AppletWithoutChangesPopup/AppletWithoutChangesPopup.types.ts
  src/modules/Builder/components/Popups/AppletWithoutChangesPopup/index.ts
  src/modules/Builder/components/index.ts
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.hooks.ts
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.tsx
  src/redux/store/reducers.ts
  src/resources/app-en.json
  src/resources/app-fr.json
  src/routes/index.tsx
  src/shared/components/Banner/Banner.styles.ts
  src/shared/components/Banner/Banner.test.tsx
  src/shared/components/Banner/Banner.tsx
  src/shared/components/Banner/index.ts
  src/shared/components/Banners/Banner/Banner.const.tsx
  src/shared/components/Banners/Banner/Banner.test.tsx
  src/shared/components/Banners/Banner/Banner.tsx
  src/shared/components/Banners/Banner/Banner.types.ts
  src/shared/components/Banners/Banner/index.ts
  src/shared/components/Banners/Banners.test.tsx
  src/shared/components/Banners/Banners.tsx
  src/shared/components/Banners/VersionWarningBanner/VersionWarningBanner.const.ts
  src/shared/components/Banners/VersionWarningBanner/VersionWarningBanner.test.tsx
  src/shared/components/Banners/VersionWarningBanner/VersionWarningBanner.tsx
  src/shared/components/Banners/VersionWarningBanner/index.ts
  src/shared/components/Banners/index.ts
  src/shared/components/index.ts
  src/shared/hooks/index.ts
  src/shared/hooks/useSessionBanners.test.ts
  src/shared/hooks/useSessionBanners.ts
  src/shared/hooks/useWindowFocus.test.ts
  src/shared/hooks/useWindowFocus.ts
  src/shared/layouts/BaseLayout/components/TopBar/TopBar.tsx
  src/shared/state/Banners/Banners.reducer.ts
  src/shared/state/Banners/Banners.schema.ts
  src/shared/state/Banners/Banners.state.tsx
  src/shared/state/Banners/index.ts
  src/shared/state/index.ts
  src/shared/styles/theme.ts
  src/svgSprite.ts
Labels: enhancement

#1491 M2-5259: [Data Export] NKI RS2 Daily Activities (New) export is failing for migrated data
  src/modules/Dashboard/hooks/useDecryptedActivityData.ts
Labels: bug, release bug

#1492 Sync: merge main into develop
  src/modules/Dashboard/hooks/useDecryptedActivityData.ts
Labels: sync (main to develop)

#1477 M2-5046: [Admin] Add "None" option to the Multiple Selection Item in the Builder
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SelectionOption/SelectionOption.test.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SelectionOption/SelectionOption.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/SelectionOption/SelectionOption.types.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/OptionalItemsAndSettings/OptionalItemsAndSettings.hooks.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/OptionalItemsAndSettings/OptionalItemsAndSettings.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/OptionalItemsAndSettings/OptionalItemsAndSettings.types.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__tests__/ItemConfigurationSingleMultiSelect.test.tsx
  src/modules/Dashboard/features/Applet/TransferOwnership/TransferOwnership.test.tsx
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/state/Applet/Applet.schema.ts
Labels: enhancement

#1488 M2-4430: [Admin panel Rewriting] Add data-testid attributes on Summary page
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Subscales/ActivityCompletionScores/ActivityCompletionScores.const.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Subscales/ActivityCompletionScores/ActivityCompletionScores.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Subscales/Subscale/Subscale.tsx
Labels: enhancement

#1490 M2-4759: [Admin Panel] Summary tab: "Respondent skipped the response" message is shown for hidden Text item
  src/modules/Dashboard/hooks/useDecryptedActivityData.ts
Labels: bug

#1487 M2-5078: [Admin] Mixpanel Tracking: Applet ID in event properties
  src/modules/Builder/features/ActivityFlowSettings/ActivityFlowSettings.tsx
  src/modules/Builder/features/ActivitySettings/ActivitySettings.tsx
  src/modules/Builder/features/ActivitySettings/ActivitySettings.utils.tsx
  src/modules/Builder/features/BuilderAppletSettings/BuilderAppletSettings.utils.tsx
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.tsx
  src/modules/Dashboard/features/Applet/DashboardAppletSettings/DashboardAppletSettings.utils.tsx
  src/modules/Dashboard/features/Applet/Popups/DuplicatePopups/DuplicatePopups.tsx
  src/modules/Dashboard/features/Applet/Popups/TransferOwnershipPopup/TransferOwnershipPopup.tsx
  src/modules/Dashboard/features/Respondents/Popups/DataExportPopup/DataExportPopup.tsx
  src/shared/features/AppletSettings/EditAppletSetting/EditAppletSetting.tsx
  src/shared/features/AppletSettings/TransferOwnershipSetting/TransferOwnershipSetting.tsx
  src/shared/hooks/index.ts
  src/shared/hooks/useTransferOwnership.test.ts
  src/shared/hooks/useTransferOwnership.ts
Labels: enhancement

#1498 M2-5098: Rewrite File upload functionality (without conversion)
  src/modules/Builder/components/MediaUploader/MediaUploader.hooks.test.ts
  src/modules/Builder/components/MediaUploader/MediaUploader.hooks.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/AudioPlayer/AudioPlayer.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/AudioPlayer/AudioPlayer.utils.ts
  src/modules/Dashboard/features/Applet/Popups/DeletePopup/DeletePopup.tsx
  src/shared/api/api.const.ts
  src/shared/api/api.ts
  src/shared/api/api.types.ts
  src/shared/components/CropPopup/CropPopup.tsx
  src/shared/components/CropPopup/CropPopup.types.ts
  src/shared/components/MarkDownEditor/extensions/Extensions.hooks.ts
  src/shared/components/Uploader/Uploader.test.tsx
  src/shared/components/Uploader/Uploader.tsx
  src/shared/hooks/index.ts
  src/shared/hooks/useMediaUpload/index.ts
  src/shared/hooks/useMediaUpload/useMediaUpload.test.ts
  src/shared/hooks/useMediaUpload/useMediaUpload.ts
  src/shared/hooks/useMediaUpload/useMediaUpload.types.ts
  src/shared/hooks/useMediaUpload/useMediaUpload.utils.test.ts
  src/shared/hooks/useMediaUpload/useMediaUpload.utils.ts
  src/shared/utils/getMediaName.test.ts
  src/shared/utils/getMediaName.ts
  src/shared/utils/index.ts
Labels: enhancement

#1152 M2-2591: Update AP to correspond Web app v.2.5
  src/modules/Builder/features/ActivityAbout/ActivityAbout.test.tsx
  src/modules/Builder/features/ActivityAbout/ActivityAbout.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/GroupedSelectSearchController/GroupedSelectSearchController.utils.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ItemConfiguration.const.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ItemConfiguration.hooks.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__mocks__/mock.tsx
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.schema.ts
  src/resources/app-en.json
  src/resources/app-fr.json
Labels: enhancement

#1505 M2-5335: [Admin] Add feature flag for "None" option
  src/modules/Builder/features/ActivityItems/ItemConfiguration/OptionalItemsAndSettings/OptionalItemsAndSettings.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__tests__/ItemConfigurationSingleMultiSelect.test.tsx
  src/shared/utils/index.ts
  src/shared/utils/testUtils.ts
Labels: enhancement

#1502 M2-1272: [Admin Panel] Calendar: Import default/individual schedule popup: Wrong color of the Update Schedule button
  src/modules/Dashboard/features/Applet/Schedule/ImportSchedulePopup/ImportSchedule.const.tsx
  src/modules/Dashboard/features/Applet/Schedule/ImportSchedulePopup/ImportSchedulePopup.test.tsx
  src/shared/components/Modal/Modal.tsx
Labels: bug

#1503 M2-5316: [Admin Panel] Logging Raw Responses (with hidden Items) for QA in debugMode
  src/modules/Dashboard/hooks/useDecryptedActivityData.ts
  src/shared/utils/exportData/prepareData.ts
Labels: enhancement

#1489 M2-5232: [Data export] Wrong value in activity journey for mobile answers
  src/shared/consts.tsx
  src/shared/types/answer.ts
  src/shared/utils/exportData/parseResponseValue.test.ts
  src/shared/utils/exportData/parseResponseValue.ts
Labels: bug

#1514 Sync: merge main[v1.13.2] into develop
  src/modules/Builder/features/ActivityAbout/ActivityAbout.test.tsx
  src/modules/Builder/features/ActivityAbout/ActivityAbout.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/GroupedSelectSearchController/GroupedSelectSearchController.utils.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ItemConfiguration.const.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ItemConfiguration.hooks.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/OptionalItemsAndSettings/OptionalItemsAndSettings.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__mocks__/mock.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__tests__/ItemConfigurationSingleMultiSelect.test.tsx
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.schema.ts
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/utils/index.ts
  src/shared/utils/testUtils.ts
Labels: sync (main to develop)

#1507 M2-5309: change Banner `data-testid`s
  src/modules/Builder/features/ReportConfigSetting/ReportConfigSetting.test.tsx
  src/modules/Builder/features/ReportConfigSetting/ReportConfigSetting.tsx
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.hooks.test.tsx
  src/modules/Dashboard/features/Applet/Popups/DeletePopup/DeletePopup.test.tsx
  src/modules/Dashboard/features/Applet/Popups/DeletePopup/DeletePopup.tsx
  src/modules/Dashboard/features/Applet/Popups/DuplicatePopups/DuplicatePopups.test.tsx
  src/modules/Dashboard/features/Applet/Popups/DuplicatePopups/DuplicatePopups.tsx
  src/modules/Dashboard/features/Applet/Popups/PublishConcealAppletPopup/PublishConcealAppletPopup.test.tsx
  src/modules/Dashboard/features/Applet/Popups/PublishConcealAppletPopup/PublishConcealAppletPopup.tsx
  src/modules/Dashboard/features/Applet/Popups/TransferOwnershipPopup/TransferOwnershipPopup.test.tsx
  src/modules/Dashboard/features/Applet/Popups/TransferOwnershipPopup/TransferOwnershipPopup.tsx
  src/modules/Dashboard/features/Managers/Managers.tsx
  src/modules/Dashboard/features/Respondents/Popups/EditRespondentPopup/EditRespondentPopup.test.tsx
  src/modules/Dashboard/features/Respondents/Popups/EditRespondentPopup/EditRespondentPopup.tsx
  src/shared/components/Banners/Banner/Banner.test.tsx
  src/shared/components/Banners/Banner/Banner.tsx
  src/shared/components/Banners/Banner/Banner.types.ts
  src/shared/components/Banners/FileSizeExceededBanner/FileSizeExceededBanner.test.tsx
  src/shared/components/Banners/FileSizeExceededBanner/FileSizeExceededBanner.tsx
  src/shared/components/Banners/IncorrectFileBanner/IncorrectFileBanner.test.tsx
  src/shared/components/Banners/IncorrectFileBanner/IncorrectFileBanner.tsx
  src/shared/components/Banners/SaveSuccessBanner/SaveSuccessBanner.test.tsx
  src/shared/components/Banners/SaveSuccessBanner/SaveSuccessBanner.tsx
  src/shared/components/Banners/TransferOwnershipSuccessBanner/TransferOwnershipSuccessBanner.test.tsx
  src/shared/components/Banners/TransferOwnershipSuccessBanner/TransferOwnershipSuccessBanner.tsx
  src/shared/components/Banners/VersionWarningBanner/VersionWarningBanner.test.tsx
  src/shared/components/Banners/VersionWarningBanner/VersionWarningBanner.tsx
  src/shared/components/FormComponents/EditorController/EditorController.tsx
  src/shared/components/Uploader/Uploader.tsx
  src/shared/features/AppletSettings/DataRetentionSetting/DataRetention.test.tsx
  src/shared/features/AppletSettings/DataRetentionSetting/DataRetention.tsx
  src/shared/features/AppletSettings/DeleteAppletSetting/DeleteAppletSetting.test.tsx
  src/shared/features/AppletSettings/DuplicateAppletSettings/DuplicateAppletSettings.test.tsx
  src/shared/features/AppletSettings/TransferOwnershipSetting/TransferOwnershipSetting.test.tsx
  src/shared/features/AppletSettings/TransferOwnershipSetting/TransferOwnershipSetting.tsx
  src/shared/hooks/useTransferOwnership.test.ts
  src/shared/hooks/useTransferOwnership.ts
  src/shared/utils/expectBanner.ts
Labels: tests

#1512 M2-4656: [Admin Panel] Red dot and validation message is not disappeared after the error is fixed
  src/modules/Builder/components/ConditionRow/ConditionRow.tsx
  src/modules/Builder/components/ConditionRow/ConditionRow.utils.ts
Labels: bug

#1518 M2-5422: [Admin] Activate the "None" option feature
  src/modules/Builder/features/ActivityItems/ItemConfiguration/OptionalItemsAndSettings/OptionalItemsAndSettings.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__tests__/ItemConfigurationSingleMultiSelect.test.tsx
Labels: enhancement

#1523 M2-5488: [Admin Panel] Data Export is failed if Single/Multiple selection item is included in Sub-scales culculation and is hidden
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Subscales/Subscales.utils.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Subscales/Subscales.utils.ts
  src/shared/utils/exportData/getSubscales.test.ts
  src/shared/utils/exportData/getSubscales.ts
Labels: release bug

#1524 M2-5203: [Cherry-picked from develop] Change password form and route
  src/modules/Auth/api/api.ts
  src/modules/Auth/api/api.types.ts
  src/modules/Auth/features/Login/Banners/PasswordResetSuccessfulBanner/PasswordResetSuccessfulBanner.tsx
  src/modules/Auth/features/Login/Banners/PasswordResetSuccessfulBanner/index.ts
  src/modules/Auth/features/Login/Banners/index.ts
  src/modules/Auth/features/Login/LoginForm/LoginForm.tsx
  src/modules/Auth/features/RecoverPassword/RecoverForm/RecoverForm.schema.ts
  src/modules/Auth/features/RecoverPassword/RecoverForm/RecoverForm.styles.ts
  src/modules/Auth/features/RecoverPassword/RecoverForm/RecoverForm.tsx
  src/modules/Auth/features/RecoverPassword/RecoverForm/RecoverForm.types.ts
  src/modules/Auth/features/RecoverPassword/RecoverForm/index.ts
  src/modules/Auth/features/RecoverPassword/index.ts
  src/modules/Auth/pages/RecoverPassword/RecoverPassword.tsx
  src/modules/Auth/pages/RecoverPassword/index.ts
  src/modules/Auth/routes/routes.const.ts
  src/modules/Auth/state/Auth.thunk.ts
  src/resources/app-en.json
  src/resources/app-fr.json
  src/resources/pages.json
  src/shared/components/Banners/Banners.const.ts
  src/shared/state/Banners/Banners.schema.ts
Labels: enhancement

#1526 M2-5493: [Admin Panel] Summary tab: Error occurs if item is included in Sub-scales culculation and is hidden
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Subscales/Subscales.utils.ts
Labels: release bug

#1521 M2-5297: Modify File Upload to include conversion handling
  src/modules/Builder/components/MediaUploader/MediaUploader.hooks.test.ts
  src/modules/Builder/components/MediaUploader/MediaUploader.hooks.ts
  src/modules/Builder/components/MediaUploader/MediaUploader.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/AudioPlayer/AudioPlayerContent/AudioPlayerContent.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/AudioPlayer/RecordAudio/RecordAudio.const.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/AudioPlayer/RecordAudio/RecordAudio.hooks.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/AudioPlayer/RecordAudio/RecordAudio.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/AudioPlayer/RecordAudio/RecordAudio.types.ts
  src/shared/hooks/useAsync.ts
  src/shared/hooks/useMediaUpload/useMediaUpload.const.ts
  src/shared/hooks/useMediaUpload/useMediaUpload.test.ts
  src/shared/hooks/useMediaUpload/useMediaUpload.ts
  src/shared/hooks/useMediaUpload/useMediaUpload.types.ts
  src/shared/hooks/useMediaUpload/useMediaUpload.utils.test.ts
  src/shared/hooks/useMediaUpload/useMediaUpload.utils.ts
Labels: enhancement, done

#1511 M2-4655: [Admin Panel] Validation error doesnt disappear when section/score/score condition name becomes unique
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ItemConfiguration.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreCondition/ScoreCondition.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreCondition/ScoreCondition.types.ts
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionContent/SectionContent.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionScoreCommonFields/SectionScoreCommonFields.tsx
  src/modules/Builder/features/ActivitySettings/SubscalesConfiguration/SubscaleContent/SubscaleContent.tsx
  src/modules/Builder/features/ActivitySettings/SubscalesConfiguration/SubscalesConfiguration.test.tsx
  src/modules/Builder/features/ActivitySettings/TitleComponent/TitleComponent.tsx
  src/modules/Builder/hooks/index.ts
  src/modules/Builder/hooks/useCheckAndTriggerOnNameUniqueness.ts
Labels: bug

#1533 M2-5547: [Admin panel] Javascript error on Scores&reports page - page does not load
  src/modules/Builder/features/ActivitySettings/TitleComponent/TitleComponent.tsx
  src/modules/Builder/hooks/useCheckAndTriggerOnNameUniqueness.ts
Labels: release bug
