Repository ChildMindInstitute/mindlogger-admin, pull requests merged in 2024-05, with the labels that each got.

#1694 Release/1.24.0
  src/modules/Builder/consts.ts
  src/modules/Builder/features/ActivityItems/LeftBar/DraggableItems/DraggableItems.tsx
  src/modules/Builder/features/ActivityItems/LeftBar/LeftBar.tsx
  src/modules/Builder/features/ActivityItemsFlow/ItemFlow/ItemFlow.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreCondition/ScoreCondition.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/ScoreContent/ScoreContent.tsx
  src/modules/Builder/features/ActivitySettings/ScoresAndReports/SectionContent/SectionContent.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/MultiScatterChart/MultiScatterChart.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/MultiScatterChart/MultiScatterChart.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/MultipleSelectionChart/MultipleSelectionChart.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/MultipleSelectionChart/MultipleSelectionChart.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/MultipleSelectionChart/index.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/ResponseOptions.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/ResponseOptions.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/ResponseOptions.types.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/ResponseOptions.utils.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ResponseOptions/ResponseOptions.utils.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/RespondentDataSummary.const.ts
  src/shared/components/DatePicker/DatePicker.tsx
  src/shared/components/DatePicker/DatePicker.types.ts
  src/shared/components/FormComponents/EditorController/Editor/Editor.hooks.ts
  src/shared/components/FormComponents/EditorController/Editor/Editor.tsx
  src/shared/components/FormComponents/EditorController/Editor/Editor.types.ts
  src/shared/components/MarkDownEditor/MarkDownEditor.utils.ts
  src/shared/consts.tsx
  src/shared/hooks/useStaticContent.ts
Labels: release

#1716 feat: enable feature approach 2 (M2-6577)
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/Drawing/DrawingContent/DrawingContent.test.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/Drawing/DrawingContent/DrawingContent.tsx
  src/resources/app-en.json
  src/resources/app-fr.json
Labels: enhancement

#1718 feat: set flag ON by default for new applets (M2-6580)
  src/modules/Builder/features/ActivityItems/ItemConfiguration/GroupedSelectSearchController/GroupedSelectSearchController.test.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/GroupedSelectSearchController/GroupedSelectSearchController.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/GroupedSelectSearchController/GroupedSelectSearchController.types.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ItemConfiguration.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__mocks__/mock.tsx
Labels: enhancement

#1708 Release/1.25.0
  src/modules/Builder/features/ActivityItems/ItemConfiguration/GroupedSelectSearchController/GroupedSelectSearchController.test.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/GroupedSelectSearchController/GroupedSelectSearchController.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/GroupedSelectSearchController/GroupedSelectSearchController.types.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/Drawing/DrawingContent/DrawingContent.test.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/Drawing/DrawingContent/DrawingContent.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ItemConfiguration.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__mocks__/mock.tsx
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.utils.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.tsx
  src/modules/Dashboard/features/Managers/Managers.tsx
  src/modules/Dashboard/features/RespondentData/RespondentData.const.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Feedback/FeedbackReviews/FeedbackReviews.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/RespondentDataReview.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/RespondentDataReview.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/ScatterChart/ChartTooltip/ChartTooltip.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/ScatterChart/ChartTooltip/ChartTooltip.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/ScatterChart/ChartTooltip/ChartTooltip.utils.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/Charts/ScatterChart/ChartTooltip/ChartTooltip.utils.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/utils/compareActivityItem.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/utils/compareActivityItem.ts
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/components/NoPermissionPopup/NoPermissionPopup.hooks.test.ts
  src/shared/components/NoPermissionPopup/NoPermissionPopup.hooks.ts
  src/shared/components/NoPermissionPopup/NoPermissionPopup.test.tsx
  src/shared/state/ForbiddenState/ForbiddenState.reducer.ts
  src/shared/state/ForbiddenState/ForbiddenState.schema.ts
  src/shared/state/ForbiddenState/ForbiddenState.state.tsx
Labels: release

#1720 chore: sync release branch to the develop branch
  src/modules/Builder/features/ActivityItems/ItemConfiguration/GroupedSelectSearchController/GroupedSelectSearchController.test.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/GroupedSelectSearchController/GroupedSelectSearchController.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/GroupedSelectSearchController/GroupedSelectSearchController.types.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/Drawing/DrawingContent/DrawingContent.test.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/Drawing/DrawingContent/DrawingContent.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ItemConfiguration.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__mocks__/mock.tsx
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.utils.ts
  src/resources/app-en.json
  src/resources/app-fr.json
Labels: sync (release to develop)

#1724 fix: Item settings: Only arrow next to the item setting name is clickable instead of the whole row (M2-6363)
  src/modules/Builder/features/ActivityItems/ItemConfiguration/Settings/ItemSettingsController/ItemSettingsGroup/ItemSettingsGroup.styles.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/Settings/ItemSettingsController/ItemSettingsGroup/ItemSettingsGroup.tsx
Labels: bug

#1725 fix: Change wording of the setting for Drawing item (M2-6586)
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/Drawing/DrawingContent/DrawingContent.test.tsx
  src/resources/app-en.json
  src/resources/app-fr.json
Labels: bug

#1733 chore: shell account update (M2-5414)
  .husky/commit-msg
  .husky/pre-push
  .husky/prepare-commit-msg
  src/modules/Builder/features/ActivityItems/ItemConfiguration/GroupedSelectSearchController/GroupedSelectSearchController.test.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/GroupedSelectSearchController/GroupedSelectSearchController.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/GroupedSelectSearchController/GroupedSelectSearchController.types.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/Drawing/DrawingContent/DrawingContent.test.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/Drawing/DrawingContent/DrawingContent.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/ItemConfiguration.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/Settings/ItemSettingsController/ItemSettingsGroup/ItemSettingsGroup.styles.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/Settings/ItemSettingsController/ItemSettingsGroup/ItemSettingsGroup.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/__mocks__/mock.tsx
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.utils.ts
  src/modules/Dashboard/features/Managers/Popups/ManagersRemoveAccessPopup/ManagersRemoveAccessPopup.test.tsx
  src/modules/Dashboard/features/Managers/Popups/ManagersRemoveAccessPopup/ManagersRemoveAccessPopup.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Feedback/AssessementItems/MultipleSelection/MultipleSelection.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Feedback/AssessementItems/MultipleSelection/MultipleSelection.tsx
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/features/AppletSettings/ExportDataSetting/ExportDataSetting.test.tsx
Labels: updating multi-informant branch

#1741 fix: updated styles for md-editor dropdown (M2-1058)
  src/shared/components/FormComponents/EditorController/Editor/Editor.utils.tsx
  src/shared/styles/theme.ts
Labels: bug

#1744 fix: [Admin Panel] It's not possible to upload lookup table with decimals scores (M2-6725)
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.schema.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
Labels: bug

#1747 feat: [Admin Panel] - Update TimeRange item contract (M2-6724)
  src/modules/Dashboard/features/RespondentData/RespondentData.utils.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentData.utils.ts
  src/shared/types/answer.ts
  src/shared/utils/exportData/parseResponseValue.test.ts
  src/shared/utils/exportData/parseResponseValue.ts
Labels: enhancement

#1732 Release 1.26.0
  .husky/commit-msg
  .husky/pre-push
  .husky/prepare-commit-msg
  src/modules/Builder/features/ActivityItems/ItemConfiguration/InputTypeItems/Drawing/DrawingContent/DrawingContent.test.tsx
  src/modules/Builder/features/ActivityItems/ItemConfiguration/Settings/ItemSettingsController/ItemSettingsGroup/ItemSettingsGroup.styles.ts
  src/modules/Builder/features/ActivityItems/ItemConfiguration/Settings/ItemSettingsController/ItemSettingsGroup/ItemSettingsGroup.tsx
  src/modules/Dashboard/features/Managers/Popups/ManagersRemoveAccessPopup/ManagersRemoveAccessPopup.test.tsx
  src/modules/Dashboard/features/Managers/Popups/ManagersRemoveAccessPopup/ManagersRemoveAccessPopup.tsx
  src/modules/Dashboard/features/RespondentData/RespondentData.utils.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentData.utils.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Feedback/AssessementItems/MultipleSelection/MultipleSelection.test.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/Feedback/AssessementItems/MultipleSelection/MultipleSelection.tsx
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/types/answer.ts
  src/shared/utils/exportData/parseResponseValue.test.ts
  src/shared/utils/exportData/parseResponseValue.ts
Labels: release

#1749 chore: sync release branch to the develop branch
  src/modules/Dashboard/features/RespondentData/RespondentData.utils.test.ts
  src/modules/Dashboard/features/RespondentData/RespondentData.utils.ts
  src/shared/types/answer.ts
  src/shared/utils/exportData/parseResponseValue.test.ts
  src/shared/utils/exportData/parseResponseValue.ts
Labels: sync (release to develop)

#1735 chore: adjust front-end to merge shell-account to develop branсh (M2-6673)
  src/modules/Dashboard/features/Applet/AddUser/AddUser.test.tsx
  src/modules/Dashboard/features/Applet/AddUser/AddUser.tsx
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.test.tsx
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.tsx
Labels: shell account

#1746 feat: [Admin Panel] - extend Summary row (M2-6690)
  src/modules/Builder/features/ActivityItemsFlow/ActivityItemsFlow.test.tsx
  src/modules/Builder/features/ActivityItemsFlow/ItemFlow/SummaryRow/SummaryRow.const.ts
  src/modules/Builder/features/ActivityItemsFlow/ItemFlow/SummaryRow/SummaryRow.utils.test.ts
Labels: enhancement

#1756 fix: Applet is still in the list after removing respondent (M2-6708)
  src/modules/Dashboard/features/Respondents/Popups/RemoveRespondentPopup/RemoveRespondentPopup.test.tsx
  src/modules/Dashboard/features/Respondents/Popups/RemoveRespondentPopup/RemoveRespondentPopup.tsx
Labels: shell account

#1754 feat: [Admin Panel] - add Date with conditions in Rule row (M2-6691)
  src/modules/Builder/components/ConditionRow/Condition/Condition.const.ts
  src/modules/Builder/components/ConditionRow/Condition/Condition.styles.ts
  src/modules/Builder/components/ConditionRow/Condition/Condition.tsx
  src/modules/Builder/components/ConditionRow/Condition/Condition.utils.ts
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SwitchCondition.styles.ts
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SwitchCondition.tsx
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SwitchCondition.types.ts
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SwitchCondition.utils.ts
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/index.ts
  src/modules/Builder/components/ConditionRow/ConditionRow.tsx
  src/modules/Builder/components/ConditionRow/ConditionRow.types.ts
  src/modules/Builder/components/ConditionRow/ConditionRow.utils.ts
  src/modules/Builder/features/ActivityItemsFlow/ActivityItemsFlow.test.tsx
  src/modules/Builder/features/ActivityItemsFlow/ItemFlow/ItemFlowContent/ItemFlowContent.tsx
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.utils.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/DateResponseItem/DateResponseItem.tsx
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/Report/ReportFilters/ReportFilters.tsx
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/components/DatePicker/DatePicker.tsx
  src/shared/components/DatePicker/DatePicker.types.ts
  src/shared/components/DatePicker/DatePickerInput/DatePickerInput.test.tsx
  src/shared/components/DatePicker/DatePickerInput/DatePickerInput.tsx
  src/shared/components/DatePicker/DatePickerInput/DatePickerInput.types.ts
  src/shared/features/AppletSettings/ExportDataSetting/Popups/ExportSettingsPopup/ExportSettingsPopup.tsx
  src/shared/state/Applet/Applet.schema.ts
  src/shared/utils/dateFormat.ts
Labels: enhancement

#1758 feat: [Admin Panel] - add Number Selection with conditions in Rule row (M2-6693)
  src/modules/Builder/components/ConditionRow/Condition/Condition.const.ts
  src/modules/Builder/components/ConditionRow/Condition/Condition.types.ts
  src/modules/Builder/components/ConditionRow/Condition/Condition.utils.ts
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SwitchCondition.tsx
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SwitchCondition.utils.ts
  src/modules/Builder/components/ConditionRow/ConditionRow.types.ts
  src/modules/Builder/components/ConditionRow/ConditionRow.utils.ts
  src/modules/Builder/features/ActivityItemsFlow/ActivityItemsFlow.test.tsx
Labels: enhancement

#1768 feat: [Admin Panel] - add Time with conditions in Rule row (M2-6699)
  src/modules/Builder/components/ConditionRow/Condition/Condition.const.ts
  src/modules/Builder/components/ConditionRow/Condition/Condition.utils.ts
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SwitchCondition.const.ts
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SwitchCondition.styles.ts
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SwitchCondition.tsx
  src/modules/Builder/components/ConditionRow/ConditionRow.utils.ts
  src/modules/Builder/features/ActivityItemsFlow/ActivityItemsFlow.const.ts
  src/modules/Builder/features/ActivityItemsFlow/ActivityItemsFlow.test.tsx
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.schema.ts
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/components/TimePicker/TimePicker.tsx
  src/shared/components/TimePicker/TimePicker.types.ts
Labels: enhancement
