Repository ChildMindInstitute/mindlogger-admin, pull requests merged in 2024-06, with the labels that each got.

#1753 Release 1.27.0
  src/modules/Builder/features/Activities/Activities.utils.test.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/GeneralSettings/ButtonsScreen/ButtonsContent/ButtonsContent.utils.test.ts
  src/modules/Builder/features/PerformanceTasks/Flanker/GeneralSettings/StimulusScreen/StimulusContent/DeleteStimulusPopup/DeleteStimulusPopup.test.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/BlockSequences/BlockSequencesContent/BlockSequencesContent.utils.test.ts
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/BlockSequences/BlockSequencesContent/ImportSequencesPopup/ImportSequencesPopup.hooks.test.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/BlockSequences/BlockSequencesContent/ImportSequencesPopup/ImportSequencesPopup.utils.test.tsx
  src/modules/Builder/features/PerformanceTasks/Flanker/RoundSettings/RoundOptions/RoundOptions.utils.test.tsx
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.schema.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
  src/modules/Dashboard/features/Applet/AddUser/AddUser.test.tsx
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.const.ts
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.hooks.test.ts
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.tsx
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.utils.test.ts
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.utils.ts
  src/shared/components/FormComponents/EditorController/Editor/Editor.utils.tsx
  src/shared/features/SwitchWorkspace/SwitchWorkspace.utils.test.ts
  src/shared/features/SwitchWorkspace/WorkspaceGroup/WorkspaceGroup.test.tsx
  src/shared/features/SwitchWorkspace/WorkspaceImage/WorkspaceImage.test.tsx
  src/shared/styles/theme.ts
Labels: release

#1770 feat: [Admin Panel] - add Time Range with conditions in Rule row (M2-6701)
  src/modules/Builder/components/ConditionRow/Condition/Condition.const.ts
  src/modules/Builder/components/ConditionRow/Condition/Condition.test.tsx
  src/modules/Builder/components/ConditionRow/Condition/Condition.tsx
  src/modules/Builder/components/ConditionRow/Condition/Condition.types.ts
  src/modules/Builder/components/ConditionRow/Condition/Condition.utils.ts
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SwitchCondition.tsx
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SwitchCondition.types.ts
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SwitchCondition.utils.ts
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/TimeCondition/TimeCondition.tsx
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/TimeCondition/TimeCondition.types.ts
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/TimeCondition/index.ts
  src/modules/Builder/components/ConditionRow/ConditionRow.tsx
  src/modules/Builder/components/ConditionRow/ConditionRow.utils.ts
  src/modules/Builder/features/ActivityItemsFlow/ActivityItemsFlow.test.tsx
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.schema.ts
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/state/Applet/Applet.schema.ts
Labels: enhancement

#1779 feat: [Admin Panel] - add Single Selection per Row + Multiple Selection per Row with conditions in Rule row, (M2-6702, M2-6703)
  src/modules/Builder/components/ConditionRow/Condition/Condition.const.ts
  src/modules/Builder/components/ConditionRow/Condition/Condition.tsx
  src/modules/Builder/components/ConditionRow/Condition/Condition.types.ts
  src/modules/Builder/components/ConditionRow/Condition/Condition.utils.ts
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SingleMultiScoreCondition/SingleMultiScoreCondition.tsx
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SingleMultiScoreCondition/SingleMultiScoreCondition.types.ts
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SingleMultiScoreCondition/index.ts
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SwitchCondition.tsx
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SwitchCondition.types.ts
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SwitchCondition.utils.ts
  src/modules/Builder/components/ConditionRow/ConditionRow.utils.ts
  src/modules/Builder/features/ActivityItemsFlow/ActivityItemsFlow.test.tsx
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.schema.ts
  src/shared/components/TimePicker/TimePicker.tsx
  src/shared/state/Applet/Applet.schema.ts
Labels: enhancement

#1786 feat: [Admin] Populate Mixpanel events with Applet ID (M2-6776)
  src/modules/Builder/features/Activities/Activities.tsx
  src/modules/Builder/features/ActivitySettings/ActivitySettings.tsx
  src/modules/Builder/features/ActivitySettings/ActivitySettings.types.ts
  src/modules/Builder/features/ActivitySettings/ActivitySettings.utils.tsx
  src/modules/Builder/features/BuilderAppletSettings/BuilderAppletSettings.tsx
  src/modules/Builder/features/BuilderAppletSettings/BuilderAppletSettings.types.ts
  src/modules/Builder/features/BuilderAppletSettings/BuilderAppletSettings.utils.test.tsx
  src/modules/Builder/features/BuilderAppletSettings/BuilderAppletSettings.utils.tsx
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.hooks.ts
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.tsx
  src/modules/Dashboard/features/Applet/AddUser/AddUserForm/AddUserForm.tsx
  src/modules/Dashboard/features/Applet/AddUser/LinkGenerator/LinkGenerator.tsx
  src/modules/Dashboard/features/Applet/DashboardAppletSettings/DashboardAppletSettings.tsx
  src/modules/Dashboard/features/Applet/DashboardAppletSettings/DashboardAppletSettings.types.ts
  src/modules/Dashboard/features/Applet/DashboardAppletSettings/DashboardAppletSettings.utils.test.tsx
  src/modules/Dashboard/features/Applet/DashboardAppletSettings/DashboardAppletSettings.utils.tsx
  src/modules/Dashboard/features/Applet/Popups/DuplicatePopups/DuplicatePopups.tsx
  src/modules/Dashboard/features/Applet/Popups/TransferOwnershipPopup/TransferOwnershipPopup.tsx
  src/modules/Dashboard/features/Applet/Schedule/CreateEventPopup/CreateEventPopup.tsx
  src/modules/Dashboard/features/Applet/Schedule/EventForm/EventForm.tsx
  src/modules/Dashboard/features/Applet/Schedule/ImportSchedulePopup/ImportSchedulePopup.tsx
  src/modules/Dashboard/features/Applet/Schedule/Legend/Legend.tsx
  src/modules/Dashboard/features/Applets/AppletsTable/AppletItem/AppletItem.tsx
  src/modules/Dashboard/features/Respondents/Popups/DataExportPopup/DataExportPopup.tsx
  src/modules/Dashboard/features/Respondents/Popups/ScheduleSetupPopup/ScheduleSetupPopup.tsx
  src/modules/Dashboard/features/Respondents/Respondents.tsx
  src/modules/Dashboard/pages/Applet/Applet.hooks.tsx
  src/modules/Library/features/Applet/Applet.tsx
  src/modules/Library/features/AppletDetails/AppletDetails.tsx
  src/shared/components/NavigationMenu/Actions/Actions.tsx
  src/shared/components/Password/EnterAppletPassword/EnterAppletPassword.tsx
  src/shared/features/AppletSettings/EditAppletSetting/EditAppletSetting.tsx
  src/shared/features/AppletSettings/TransferOwnershipSetting/TransferOwnershipSetting.tsx
  src/shared/hooks/useTransferOwnership.test.ts
  src/shared/hooks/useTransferOwnership.ts
Labels: enhancement

#1755 feat: LORIS - feature flag integration (M2-6636)
  .env.example
  package-lock.json
  package.json
  src/App.tsx
  src/index.tsx
  src/modules/Auth/state/Auth.thunk.ts
  src/modules/Builder/features/BuilderAppletSettings/BuilderAppletSettings.tsx
  src/modules/Builder/features/BuilderAppletSettings/BuilderAppletSettings.types.ts
  src/modules/Builder/features/BuilderAppletSettings/BuilderAppletSettings.utils.tsx
  src/modules/Builder/features/BuilderAppletSettings/LorisIntegrationSetting/LorisIntegrationSetting.tsx
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.hooks.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.utils.tsx
  src/modules/Builder/types/Builder.types.ts
  src/shared/consts.tsx
  src/shared/hooks/useFeatureFlags.const.ts
  src/shared/hooks/useFeatureFlags.ts
  src/shared/hooks/useLogout.ts
  src/shared/layouts/BaseLayout/components/LeftBar/LeftBar.tsx
  src/shared/state/Applet/Applet.schema.ts
  src/shared/state/Workspaces/Workspaces.schema.ts
  src/shared/types/featureFlags.ts
  src/shared/utils/featureFlags.ts
Labels: enhancement, In Progress

#1806 feat: [Admin Panel] - add Slider Rows with conditions in Rule row (M2-6704)
  src/modules/Builder/components/ConditionRow/Condition/Condition.const.ts
  src/modules/Builder/components/ConditionRow/Condition/Condition.tsx
  src/modules/Builder/components/ConditionRow/Condition/Condition.types.ts
  src/modules/Builder/components/ConditionRow/Condition/Condition.utils.ts
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SingleOrRangeNumberCondition/SingleOrRangeNumberCondition.tsx
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SingleOrRangeNumberCondition/SingleOrRangeNumberCondition.types.ts
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SingleOrRangeNumberCondition/SingleOrRangeNumberCondition.utils.ts
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SingleOrRangeNumberCondition/index.ts
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SwitchCondition.tsx
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SwitchCondition.types.ts
  src/modules/Builder/components/ConditionRow/Condition/SwitchCondition/SwitchCondition.utils.ts
  src/modules/Builder/components/ConditionRow/ConditionRow.types.ts
  src/modules/Builder/components/ConditionRow/ConditionRow.utils.ts
  src/modules/Builder/features/ActivityItemsFlow/ActivityItemsFlow.test.tsx
  src/modules/Builder/features/SaveAndPublish/SaveAndPublish.utils.ts
  src/modules/Builder/pages/BuilderApplet/BuilderApplet.schema.ts
  src/shared/components/DatePicker/DatePicker.tsx
  src/shared/components/DatePicker/DatePicker.utils.ts
  src/shared/state/Applet/Applet.schema.ts
  src/shared/utils/dateFormat.ts
Labels: enhancement

#1832 feat: Update Confusing Design on Activity Timer Creation (M2-7001)
  src/modules/Dashboard/features/Applet/Schedule/EventForm/TimersTab/TimersTab.tsx
  src/resources/app-en.json
  src/resources/app-fr.json
  src/shared/components/TimePicker/TimePicker.tsx
Labels: enhancement

#1834 fix: [Admin Panel, Report Server] Report, Subscales: Some decimal scores aren't rounded (M2-6767)
  src/shared/utils/exportData/getSubscales.test.ts
  src/shared/utils/exportData/getSubscales.ts
Labels: bug

#1833 fix: wrong appearance of NoPermissionPopup (M2-6419)
  src/shared/api/api.client.ts
  src/shared/api/api.const.ts
  src/shared/api/api.utils.test.ts
  src/shared/api/api.utils.ts
  src/shared/components/NoPermissionPopup/NoPermissionPopup.hooks.test.ts
  src/shared/components/NoPermissionPopup/NoPermissionPopup.hooks.ts
  src/shared/hooks/usePermissions.test.tsx
  src/shared/hooks/usePermissions.tsx
Labels: bug

#1839 fix: Activity answers not preselected without Flows in DataViz (M2-7174)
  src/modules/Dashboard/features/RespondentData/RespondentDataReview/hooks/useReviewActivitiesAndFlows/useReviewActivitiesAndFlows.ts
  src/modules/Dashboard/features/RespondentData/RespondentDataSummary/RespondentDataSummary.tsx
Labels: release bug
